### ISSUE TITLE
Update README and Install Guide

### ISSUE THREAD

**Issue by thw26** [ferion11/LogosLinuxInstaller#114]
The README needs to be updated to be more of a standard README for use of the script.

I have copied the current README's material to the wiki and flagged it as outdated. It will need to be updated for what will be called the 3.x series.

**Comment by shadyalfred** [comment]
Does this mean this snippet not work anymore?
```sh
DOWNLOADED_RESOURCES=${HOME}/Downloads INSTALLDIR=/tmp/logosBibleTemp ./LogosLinuxInstaller.sh
```

**Comment by thw26** [comment]
Hello,

This issue has been closed since March 6th.

If you are referring to the new Python release, please submit your query in that repository.
