### ISSUE TITLE
Several Errors during Install

### ISSUE THREAD

**Issue by albolea** [ferion11/LogosLinuxInstaller#12]
Hey Ferion11.

Thank you so much for the initiative!

I tried today to install on Ubuntu 20.4 but it didn't work.

I unzipped it on my Downloads and on the terminal I use:

 sh Install_AppImageWine_and_Logos.sh 

end I got this result:

Searching for dependencies:
* Zenity is installed!
* wget is installed!
* command find is installed!
* command sed is installed!
* command grep is installed!
Starting Zenity GUI...
/home/myuser/AppImage/wine-i386_x86_64-archlinux.AppImage exist. Using it...
Segmentation fault
Segmentation fault
/tmp/workingLogosTemp/winetricks: 2472: Syntax error: end of file unexpected (expecting "}")
/tmp/workingLogosTemp/winetricks: 3952: Syntax error: Unterminated quoted string
/tmp/workingLogosTemp/winetricks: 3952: Syntax error: Unterminated quoted string
/tmp/workingLogosTemp/winetricks: 3952: Syntax error: Unterminated quoted string
/tmp/workingLogosTemp/winetricks: 3952: Syntax error: Unterminated quoted string
/tmp/workingLogosTemp/winetricks: 3952: Syntax error: Unterminated quoted string
/tmp/workingLogosTemp/winetricks: 3952: Syntax error: Unterminated quoted string
/tmp/workingLogosTemp/winetricks: 3952: Syntax error: Unterminated quoted string
/tmp/workingLogosTemp/winetricks: 3952: Syntax error: Unterminated quoted string
/tmp/workingLogosTemp/winetricks: 3952: Syntax error: Unterminated quoted string
/tmp/workingLogosTemp/winetricks: 3952: Syntax error: Unterminated quoted string
/tmp/workingLogosTemp/winetricks: 3952: Syntax error: Unterminated quoted string
/tmp/workingLogosTemp/winetricks: 3952: Syntax error: Unterminated quoted string
/tmp/workingLogosTemp/winetricks: 3952: Syntax error: Unterminated quoted string
/tmp/workingLogosTemp/winetricks: 3952: Syntax error: Unterminated quoted string
/tmp/workingLogosTemp/winetricks: 3952: Syntax error: Unterminated quoted string
/tmp/workingLogosTemp/winetricks: 3952: Syntax error: Unterminated quoted string
/tmp/workingLogosTemp/winetricks: 3952: Syntax error: Unterminated quoted string
/tmp/workingLogosTemp/winetricks: 3952: Syntax error: Unterminated quoted string
/tmp/workingLogosTemp/winetricks: 3952: Syntax error: Unterminated quoted string
/tmp/workingLogosTemp/winetricks: 3952: Syntax error: Unterminated quoted string
/tmp/workingLogosTemp/winetricks: 3952: Syntax error: Unterminated quoted string
/tmp/workingLogosTemp/winetricks: 3952: Syntax error: Unterminated quoted string
/tmp/workingLogosTemp/winetricks: 3952: Syntax error: Unterminated quoted string
/tmp/workingLogosTemp/winetricks: 3952: Syntax error: Unterminated quoted string
Segmentation fault
find: ‘/home/myuser/.wine32’: No such file or directory
chmod: cannot access '/tmp/worki': No such file or directory
chmod: cannot access 'gLogosTemp/Logos.sh': No such file or directory
Cleaning all temp files...
done
Install_AppImageWine_and_Logos.sh: 281: /home/myuser/Desktop/Logos.sh: Permission denied
End!

Any idea why?

Renato Albolea

**Comment by albolea** [comment]
I executed the Unistall script and reboot the computer.
Than I executed again the script to install.... It is apparently working this time......

**Comment by ferion11** [comment]
The "Segmentation fault" maybe was caused by one error on the download, but the "Permission denied" on your Desktop folder made me wander if it was one of the Ubuntu AppArmor security bugs behaviors that got fixed by some update.
