### ISSUE TITLE
Moving to your latest release

### ISSUE THREAD

**Issue by Gene-W** [ferion11/LogosLinuxInstaller#13]
Hello again!

I'm still on one of your previous releases but unfortunately the program has stopped launching for me. Sometimes I get the blue Logos 8 loading image where it hangs, but often I don't even see that.

Would it be best for me to move to your latest release, and if so, how should I go about removing the version I have now?

Thank you for your work and for your help.

**Comment by ferion11** [comment]
Hi,
If I remember correctly (from https://github.com/ferion11/LogosLinuxInstaller/issues/4), you are using one installation made directly using your system's wine.
Versions installed with wine 5.x are being corrupted, the bottle (e.g.: $HOME/.wine), in LogosBible updates (I even had a test version that happened the same).
If your Linux installation no longer has the problem in the Filesystem in Userspace (FUSE), like reported in https://github.com/ferion11/LogosLinuxInstaller/issues/4, then I recommend you to try the portable version:
https://drive.google.com/drive/folders/1iD3flpZLIBC9S0UkNAS-lVJCizvreUgb
Just extract and run the Logos.sh inside the directory (each copy is like a new installation, so it's useful for test, and to use on portable USB devices too).

**Comment by Gene-W** [comment]
Wow, that's really cool, thanks! I see once it starts it offers to download the library. Is this something it will want to do each time as it's portable?

**Comment by ferion11** [comment]
So each copy folder will be like one independent windows installation.

**Comment by Gene-W** [comment]
Amazing! I'll download the library once I'm at work where I can use unlimited data. And wondering one more thing, where's your tip button? :)

**Comment by ferion11** [comment]
> Amazing! I'll download the library once I'm at work where I can use unlimited data. And wondering one more thing, where's your tip button? :)

Well, there isn't a "tip button". The Kingdom of God works very well without it. So don't worry, Jesus Christ is still the King.

**Comment by Gene-W** [comment]
Amen! Well I appreciate your time and your work and thank you very much!

**Comment by ferion11** [comment]
> Amen! Well I appreciate your time and your work and thank you very much!

Thank you too, I also appreciate your work :)

**Comment by Gene-W** [comment]
Hey Daniel, so sorry to return already! I started Logos today and it performed it's update, but gave me an error which returns each time I exit and restart the program. The error says, "The selected user does not have sufficient privileges to complete the setup. Please choose Administrator from the Run As ... dialog."

Rather than I poking around and breaking something, I thought better to ask if you've come across this before. :)

**Comment by ferion11** [comment]
Hi! Don't worry.
Well, unfortunately, as all internal users of Wine are administrators (having full access to everything inside the bottle), this error has no solution for now.
Did you synchronize the Logos library or copied from another installation?

**Comment by Gene-W** [comment]
Oh good, I was worried I did break something!
I synchronized the library the first time I used the portable.

**Comment by ferion11** [comment]
> Oh good, I was worried I did break something!
> I synchronized the library the first time I used the portable.

Thanks. So we have one bug here that need to be tested now. I will try to make my updates now and see.
It doesn't look like it's going to be easy, for me, this time :)

By the way, if you needed to face The Antichrist, and his army of spiritual beasts, face to face, what would you do? Expelling in the name of Jesus doesn't work, as he doesn't respect anything that bears the name of God. As far as I know, the only way out would be to manifesting glory. Praying to God, the only answer I get is "you're going to die" (and be revived later, of course).

**Comment by ferion11** [comment]
This time the problem is bigger: neither the version with Wine-Staging v4.21 nor v5.11 can update the version v8.14.0.0010 to version v8.15.0.0004 of LogosBible. And if you try, then you will get one corrupted installation.
For now, I removed the portable version. And I will work on the installer for the LogosBible v8.15.0.0004.
I'm sorry, but it seems that something fundamental has changed in this LogosBible update. I would not be surprised if all installations made with Wine were unable to make this last update.

**Comment by Gene-W** [comment]
Wow, I wish there were more I could do to help! If there is anything I could do, let me know.

As far as the Antichrist and his army go, I'll take death. He can only kill me once and then I live forever. :)

**Comment by ferion11** [comment]
> Wow, I wish there were more I could do to help! If there is anything I could do, let me know.
> 
> As far as the Antichrist and his army go, I'll take death. He can only kill me once and then I live forever. :)

Well, I plan to release new versions of the installer today (after testing everything). Unfortunately, we need to install everything again.

About the question, I agree, difficult days are ahead now. May the Lord bless us (this time, we will need a lot more).

**Comment by ferion11** [comment]
Got the v1.8 released, but I'm not sure that it will work well yet: https://github.com/ferion11/LogosLinuxInstaller/releases
After doing some tests, I got mixed results, and the portable version don't work anymore (it just crash with one error).
Sorry, but it will take some time to find out what's going on.

**Comment by Gene-W** [comment]
I still have the working portable version and have switched off automatic updates and it's working fine. If you need help testing when something is ready, I'll be around.

**Comment by ferion11** [comment]
> I still have the working portable version and have switched off automatic updates and it's working fine. If you need help testing when something is ready, I'll be around.

Thanks. I'm trying to avoid modifying the Wine code, but I have to start planning how to do that (using github+travis-ci), if I want the portable version to work again.

That said, there is one workaround that maybe work for you:
1- Make one copy of the directory of the working portable version, to test this workaround without doing anything with your original working copy.
2- Replace the Logos.sh with this one here: [Logos.sh.zip](https://github.com/ferion11/LogosLinuxInstaller/files/4972759/Logos.sh.zip)
3- Note: you will need to extract the `Logos.sh.zip` to `Logos.sh`, and maybe give it the permission for execution: `chmod +x Logos.sh`
4- Download the new Logos installer (the v8.15.0.0004 today): https://downloads.logoscdn.com/LBS8/Installer/8.15.0.0004/Logos-x86.msi
5- Then execute `./Logos.sh wine control`
6- Open the `Add/Remove Programs`, then:
7- Click to select the `Logos Bible Software`, then in Modify/Remove.
8- Follow the steps to remove the `Logos Bible Software`
9- Use the "Install" button on the `Add/Remove Programs` window to select and install the `Logos-x86.msi`. Please use the custom installation, and change the path of installation to `c:\Logos\`
10- After the installation is done, you can test the new version.
11- There's a 50% chance of working, based on my tests (I don't know why sometimes it works and sometimes don't). I hope it works for you :)

**Comment by ferion11** [comment]
By the way, about the strange question that I asked before, don't worry, God helped me with what I needed and now I'm better prepared for the new times. I look forward to the day when there will be no more sea.

**Comment by Gene-W** [comment]
As soon as I said I'll be around of course I got very busy at work and haven't even seen my laptop  for the last 2 days! I'll be able to test things if not tomorrow then Wednesday for sure.

As for the sea, something that has been pressing firmly upon me these last several weeks is to not be distracted by the storm...eyes on the Master. :)

**Comment by ferion11** [comment]
> As soon as I said I'll be around of course I got very busy at work and haven't even seen my laptop for the last 2 days! I'll be able to test things if not tomorrow then Wednesday for sure.
> 
> As for the sea, something that has been pressing firmly upon me these last several weeks is to not be distracted by the storm...eyes on the Master. :)

Don't worry about testing it. I'm reworking on the installer to make installations more like the portable versions (and fixing many things). I got one better way to test it using github+travis-ci too. I want to do one type of installation that is easy to install and to fix it without having to reinstall everything.

**Comment by ferion11** [comment]
Finished now the v2.0 release (its work like the portable version, and can work with or without the AppImage too): https://github.com/ferion11/LogosLinuxInstaller/releases
and the new instructions: https://github.com/ferion11/LogosLinuxInstaller

Now if LogosBible gets corrupted after one update, it will be easy to remove and install a new one, without having to reinstall everything, using the Windows Control Panel by running `controlPanel.sh`.

It is also easier to test as well. I am using one automated system for this now that generates images of what happened during the installation: https://github.com/ferion11/LogosLinuxInstallTests/releases

**Comment by Gene-W** [comment]
Looks like it should work well! Does 2.0 install alongside or overwrite older versions and should I run the **Uninstall_AppImageWine_and_Logos.sh** to remove previous versions, to regain space or any other reason?

**Comment by ferion11** [comment]
The v2.0 just create another independent and isolated installation like the portable version (in your `$HOME/LogosBible_Linux_P`) that can be renamed and moved. Instead of login, you could replace the `wine32bottle` dir with the old one (from the portable version) and it should work too, if you don't want to sync again.
`Uninstall_AppImageWine_and_Logos.sh` is just to remove the old v1.9 or lower if needed only (maybe after the v2.0 is working).

**Comment by ferion11** [comment]
But you will need the LogosBible update anyway, so is better to not reuse the old `wine32bottle` and just make another new installation alongside the old ones.
The new installation, like the portable one, don't have one uninstall because everything is inside the directory, so removing it should no leave any trace of it :)
