### ISSUE TITLE
v1.x and 2.x both giving me the same launch issue - Logos UI crashes almost immediately on launch

### ISSUE THREAD

**Issue by REMjn832** [ferion11/LogosLinuxInstaller#16]
First of all, THANK YOU! For all the work you put into this project, for a dummy like me especially. I had tried to get this working back in Jan/Feb this year with the older release, prior to v2.x. I had an issue where it would either crash about 5 seconds after rendering the Logos main UI, or shortly thereafter. I would try to click details on the error message, and it would just CTD. I removed that installation after a couple months of trying to fix it, I just couldn't.
Now, I tried to install the latest v2 today, and seem to be having the same problem. I run the script to start Logs, everything seems fine (there are a few nasty errors in the console output - attached), but it seems fine and then, every time about 3-5 seconds after the UI shows up, the error. And I can't click details, if I do - the dialogue disappears, and so does the UI. BUT the indexing still runs.. I will see a balloon in the upper right that says Logos indexing, and the console still shows the app is running, but the UI for Logos is just gone...

Console Ouput: https://gist.github.com/REMjn832/45fbf6c70f493f37de555513a21aa829
Note: the console will keep running, indexing, but the Logos UI is gone.
![Aug24-141740](https://user-images.githubusercontent.com/54751622/91081115-9dd5f280-e614-11ea-8793-559f08d51811.png)

Thanks very much for any help you have.

**Comment by ferion11** [comment]
> First of all, THANK YOU! For all the work you put into this project, for a dummy like me especially. I had tried to get this working back in Jan/Feb this year with the older release, prior to v2.x. I had an issue where it would either crash about 5 seconds after rendering the Logos main UI, or shortly thereafter. I would try to click details on the error message, and it would just CTD. I removed that installation after a couple months of trying to fix it, I just couldn't.

You are the image of God, and there is no god that is dummy. You are much more than you can imagine. So don't worry.

> Now, I tried to install the latest v2 today, and seem to be having the same problem. I run the script to start Logs, everything seems fine (there are a few nasty errors in the console output - attached), but it seems fine and then, every time about 3-5 seconds after the UI shows up, the error. And I can't click details, if I do - the dialogue disappears, and so does the UI. BUT the indexing still runs.. I will see a balloon in the upper right that says Logos indexing, and the console still shows the app is running, but the UI for Logos is just gone...
> 
> Console Ouput: https://gist.github.com/REMjn832/45fbf6c70f493f37de555513a21aa829
> Note: the console will keep running, indexing, but the Logos UI is gone.
...
> 
> Thanks very much for any help you have.

Now that I'm running automated tests, I'm finding all kinds of errors too :)
The main issue is in winetricks when installing dotnet (but there are other problems too).
In each test of a different version of winetricks, I run about 7 different test installations. And at the moment, some work and others fail. I can hardly get them all to work.

From your log, I can see that the dotnet installation failed, even though winetricks said it was successful.
Now I'm trying to work with the winetricks's devs to solve some of the problems.
Como eu disse em https://community.logos.com/forums/p/121/1108555.aspx#1108555
`This time the problem, on my side, is bigger`

And in those situations where there are many factors that I cannot control, I try to improve those that I can, so that when everything works again, we can have a better installation process :)

**Comment by ferion11** [comment]
I made one version to workaround the dotnet48 bugs, please try to install using it:
https://github.com/ferion11/LogosLinuxInstaller/releases/download/v2.9a-rc2/install_AppImageWine_and_Logos.sh

**Comment by REMjn832** [comment]
Thanks so much for the encouragement and support :)
I removed the old version, and ran the new version.
When I try to run either Logos.sh, or controlPanel.sh, I am getting the following:

> ❱ ./Logos.sh 
======= Running control: =======
Something went wrong trying to read the squashfs image.
Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory
Something went wrong trying to read the squashfs image.
Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory
======= control run done! =======

Note: If I just drop into the /data directory and run "wine-i386_x86_64-archlinux.AppImage", it does run the Wine configuration window. And I do use several other AppImage containers that seem to still be working good.

**Comment by ferion11** [comment]
> > ======= Running control: =======
> > Something went wrong trying to read the squashfs image.
> > Cannot mount AppImage, please check your FUSE setup.
> > You might still be able to extract the contents of this AppImage
> > if you run it with the --appimage-extract option.
> > See https://github.com/AppImage/AppImageKit/wiki/FUSE
> > for more information
> > open dir error: No such file or directory
> > Something went wrong trying to read the squashfs image.
> > Cannot mount AppImage, please check your FUSE setup.
> > You might still be able to extract the contents of this AppImage
> > if you run it with the --appimage-extract option.
> > See https://github.com/AppImage/AppImageKit/wiki/FUSE
> > for more information
> > open dir error: No such file or directory
> > ======= control run done! =======

I'm sorry to report this, but your linux FUSE (Filesystem in Userspace) installation is broken. Without it you can't use any AppImage. You should try to update your linux distribution first.
You can test, if any AppImage are working with one smaller AppImage like CPU-X:
```
wget -c https://github.com/X0rg/CPU-X/releases/download/v4.0.1/CPU-X-v4.0.1-x86_64.AppImage
chmod +x CPU-X-v4.0.1-x86_64.AppImage
./CPU-X-v4.0.1-x86_64.AppImage
```

**Comment by REMjn832** [comment]
Hi, thanks for the quick response. Actually, all of my AppImages seem to be working fine. I just rebooted to confirm there wasn't something weird in memory. But I have about 10 other AppImages, and all of them ran just fine after a reboot. I also downloaded and ran the one you suggested (CPU-X), and it worked fine as well. But the Logos.sh, still reports the same error. I also reinstalled FUSE on my distro and the same behavior for everything. 
I also tried launching the wine appImage directly, with the --appimage-extract flag, and it produced the error:

> Something went wrong trying to read the squashfs image.
Failed to open squashfs image

**Comment by ferion11** [comment]
> Hi, thanks for the quick response. Actually, all of my AppImages seem to be working fine. I just rebooted to confirm there wasn't something weird in memory. But I have about 10 other AppImages, and all of them ran just fine after a reboot. I also downloaded and ran the one you suggested (CPU-X), and it worked fine as well. But the Logos.sh, still reports the same error. I also reinstalled FUSE on my distro and the same behavior for everything.
> I also tried launching the wine appImage directly, with the --appimage-extract flag, and it produced the error:
> 
> > Something went wrong trying to read the squashfs image.
> > Failed to open squashfs image

In this case the AppImage file got corrupted, if your installation of Logos is ok, you can get another one. The default from the installer is this:
```
# from https://github.com/ferion11/Wine_Appimage/releases/tag/continuous-logos
wget -c https://github.com/ferion11/Wine_Appimage/releases/download/continuous-logos/wine-i386_x86_64-archlinux.AppImage
chmod +x wine-i386_x86_64-archlinux.AppImage
rm LogosBible_Linux_P/data/wine-i386_x86_64-archlinux.AppImage
mv wine-i386_x86_64-archlinux.AppImage LogosBible_Linux_P/data/
```

**Comment by REMjn832** [comment]
Well, sadly it produced the same error, though I was really hoping that would have been the fix. Don't worry though, I am guessing there is some latent issue on my system, and I don't mean to keep consuming your time...
One thing I was going to ask though, if possible... I am not good at bash script, and I see the Logos.sh and was hoping maybe I could somehow manually recreate the command I would need to run Logos (the AppImage and wine), but I couldn't. Is that something easy - that maybe I could use to help me troubleshoot?

Two things that may help, when I just run "./wine-i386_x86_64-archlinux.AppImage", it does load and show me the Wine configuration dialog. Also, when I used the first script (yesterday, before the update), I could get to the Logos installation portion, but now it crashes before I can install Logos. You probably already knew that, just adding more commentary.

Again, don't worry about it right now - I don't mean to monopolize your time. I am very grateful for the work you are doing to try and get Logos to work on our systems!

**Comment by ferion11** [comment]
> Well, sadly it produced the same error, though I was really hoping that would have been the fix. Don't worry though, I am guessing there is some latent issue on my system, and I don't mean to keep consuming your time...

Indeed, there seems to be some problem with the stability of FUSE in your system. The tests on travis-ci and GithubActions with the AppImage run just fine like the tests on my local machine:
Log: https://travis-ci.com/github/ferion11/LogosLinuxInstallTests/jobs/377150806
Log: https://github.com/ferion11/LogosLinuxInstallTests/runs/1024390555
Video of the testing with travis-ci: https://github.com/ferion11/LogosLinuxInstallTests/releases/download/continuous/video1.mp4

> One thing I was going to ask though, if possible... I am not good at bash script, and I see the Logos.sh and was hoping maybe I could somehow manually recreate the command I would need to run Logos (the AppImage and wine), but I couldn't. Is that something easy - that maybe I could use to help me troubleshoot?

Well, if you want to change the `Logos.sh` or `controlPanel.sh`, you could just add `--appimage-extract-and-run` on the line that call `wine` or `wineserver`, like this:
[Logos.sh.zip](https://github.com/ferion11/LogosLinuxInstaller/files/5132570/Logos.sh.zip)
[controlPanel.sh.zip](https://github.com/ferion11/LogosLinuxInstaller/files/5132571/controlPanel.sh.zip)
you will need to give execution permission after extracting too (with `chmod +x Logos.sh` and `chmod +x controlPanel.sh`)

> Two things that may help, when I just run "./wine-i386_x86_64-archlinux.AppImage", it does load and show me the Wine configuration dialog. Also, when I used the first script (yesterday, before the update), I could get to the Logos installation portion, but now it crashes before I can install Logos. You probably already knew that, just adding more commentary.
> 
> Again, don't worry about it right now - I don't mean to monopolize your time. I am very grateful for the work you are doing to try and get Logos to work on our systems!

Don't worry. This issue happens when I run the script inside a Docker container too, so I was thinking about adding this workaround, but every execution asked me to update WineBottle, so I ended up giving up because it gets harder for automated testing. But now I'm thinking of adding it again, just to be sure we have the alternative option.

**Comment by ferion11** [comment]
By the way, you don't need to change the script, you need to just export the variable APPIMAGE_EXTRACT_AND_RUN to 1:
```
export APPIMAGE_EXTRACT_AND_RUN=1
```
Do it before run the `install_AppImageWine_and_Logos.sh`, or the `Logos.sh`, or the `controlPanel.sh`

**Comment by REMjn832** [comment]
Wanted to say thank you! I have tried every installer you have released since this issue with the same result, but tried again today with v2.15, and its all working great! Logos is indexing right now. I ran the installer with the default (top) option for 32-bit appimage, and so far, so good! Thank you, thank you!

**Comment by ferion11** [comment]
Thanks to you too for the feedback :)
