### ISSUE TITLE
App Image install no longer working

### ISSUE THREAD

**Issue by jg00dman** [ferion11/LogosLinuxInstaller#178]
Today I was trying to support someone over a zoom call and we found that when selecting to use the app Image ( in console mode ) it actually used the local wine instead anyway and didn't download the app Image. This needs testing further to find a cause. The user was on wasta-linux (ubuntu based).

**Comment by thw26** [comment]
We have been discussing this issue in the chat group recently actually.

A user, Marty, reported that the issue appears to be this, and I quote:

>The problem appears to be on line 747 with whiptail (i.e. DIALOG is "whiptail"):
>`installationChoice="$($DIALOG --backtitle "${BACKTITLE}" --title "${TITLE}" --radiolist "${QUESTION_TEXT}" 0 0 0 "${WINEBIN_OPTIONS[@]}" 3>&1 1>&2 2>&3 3>&-)"`
>When I run the script, installationChoice is set to "AppImage" and no more.
>Hence, `${installArray[0]}` is set to "AppImage" only, so WINEBIN_CODE is set to "AppImage".
>And WINE_EXE is set to "" (because there is no second argument in ${installArray[0]}.
```

I needs to debug what's going on here, but most likely a variable isn't being assigned properly.

**Comment by jg00dman** [comment]
Thanks
