### ISSUE TITLE
Install not getting past first screen of msi

### ISSUE THREAD

**Issue by jg00dman** [ferion11/LogosLinuxInstaller#179]
Today while supporting a user on wasta linux, we couldn't get past the first slide of the installer. The msi loaded, we clicked next and it simply vanished but did not crash. The process never quit, no error message, no progress. We tried this with wine 8.6 staging and wine 8.7 staging. I've never seen this before. I wonder if the script has turned off wine's verbose output? If so, can we have an easy flag to reinstate it because error messages are pretty useful. Or can we have an error log?

**Comment by thw26** [comment]
You want the `-D|--debug` flag on any of the scripts; these make wine print out all the information. I just silenced it by default so people only get that feedback when requested.

I haven't seen that issue yet, other than the general removing the library catalog fix.
