### ISSUE TITLE
Beautify CLI Installer

### ISSUE THREAD

**Issue by thw26** [ferion11/LogosLinuxInstaller#185]
3.7.0 introduced the CLI only-ish installer. The output is fairly limited and meant solely to be functional, not pretty. This issue is to note that the CLI installer needs its user facing output beautified.

**Comment by Callen44** [comment]
I understand that a lot of users don't have experience with the command line, but just to clarify this will not remove any output or make information currently accessible become unassailable. For me functionality and ease of debugging is more important than ascetics. So how exactly is the CLI output going to be changed?

**Comment by thw26** [comment]
Good question!

This isn't about reducing information as it is about presentation of information. This is only for user facing output, as in: making it so the output isn't a wall of text, and when the installer requests user input, it is more clear that user interaction is required.

I gated debug information behind two flags, `-V|--verbose`, which gives basic output like "beginning some step", and for even more info, `-D|--debug`. A recent commit actually just increased the amount of information to the umpteenth degree because `-D` now sets bash's `set -x`.

You can see when those commands were introduced in the changelog.

This note is more a reminder for myself to update the presentation of the information at some point, or if someone wants to take a crack at it, they are welcome to do so and submit a PR citing this issue.

**Comment by thw26** [comment]
Should anyone feel up to the task, an example of beautifying would be to add loading spinners so CLI users know the script is running and not stalled:

https://stackoverflow.com/questions/238073/how-to-add-a-progress-bar-to-a-shell-script

**Comment by Callen44** [comment]
I'm not very good with shell scripting, I would love to do this but I won't be able to put any real time into it for a while so I can't help with this one right *now*.  I'll see if there's anything I can do in the not-so-far future, but once again I don't think It'll be a while before I can do anything. If there is anyone else in the community wink-wink who can help please say something.
