### ISSUE TITLE
Add .desktop file

### ISSUE THREAD

**Issue by zoglesby** [ferion11/LogosLinuxInstaller#19]
The install script should have a .desktop file and put it in `$HOME/.local/share/applications`. This would allow for a launcher icon in most WMs. I have one, just working on getting the logo to display, once that works I will try a PR.

**Comment by ferion11** [comment]
> The install script should have a .desktop file and put it in `$HOME/.local/share/applications`. This would allow for a launcher icon in most WMs. I have one, just working on getting the logo to display, once that works I will try a PR.

It would be a good option, but the file would have to be updated constantly, or you would lose the ability to rename the installation directory, or move it to other directories (or copy to make working backups), partitions or other linux machines, and keep it working.

Perhaps adding this option for those who don't intend to move the installation directory (maybe, more one option to the `Logos.sh`).

**Comment by ferion11** [comment]
Done at [v2.16](https://github.com/ferion11/LogosLinuxInstaller/releases).

After the installation, and you moved the installation directory to some more comfortable place, then run:
```
$ ./Logos.sh shortcut
```
Note that you will need to run this again every time that you change the installation directory (name or path), and if you have multiple installations (like one for backup) then you will need to run it for the installation that you want the `shortcut` to be updated to (it will replace the old `shortcut`).

**Comment by ferion11** [comment]
Just for the info:
If you want to use it in your current installation, just download the new installer version and run:
```
$ INSTALLDIR=/tmp/logosSkel32 ./install_AppImageWine_and_Logos.sh skel32
or to 64bits version:
$ INSTALLDIR=/tmp/logosSkel64 ./install_AppImageWine_and_Logos.sh skel64
```
And copy the script `Logos.sh` (from /tmp/logosSkel32 or /tmp/logosSkel64), and replace the one inside your installation directory.
