### ISSUE TITLE
Put Wine Bottle ".wine32" inside the AppImage

### ISSUE THREAD

**Issue by probonopd** [ferion11/LogosLinuxInstaller#2]
Why not put the WINEPREFIX ".wine32" inside the AppImage?

Have a look at how I use unionfs-fuse to do this trick :)

https://github.com/probonopd/libhookexecv/blob/a1ff356f284bb7b114671eda62798b50dfc7a30e/winedeploy.sh#L117-L139
https://github.com/probonopd/libhookexecv/blob/a1ff356f284bb7b114671eda62798b50dfc7a30e/winedeploy.sh#L26-L27

**Comment by ferion11** [comment]
If LogosBible was one traditional software, I would have done that. But it's very big (my .wine32 only for LogosBible have almost 10GB) and it's get a lot of updates. Was more than 3GB of LogosBible updates for me, only this week. And the real installation start when the user do login. It's a partial online application, with a lot of updates.
From my experience, one AppImage should be smaller than 512MB (the wine32 alone have now 323MB, and getting bigger). One time ago, I was done one AppImage of ~1GB, and it caused a lot of nightmares when updated it.
