### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by YoJames2019** [ferion11/LogosLinuxInstaller#20]
Once the installer finishes and launches the logos installer, the logos installer says that dotnet is not installed and then quits

**Comment by YoJames2019** [comment]
https://pastebin.com/xabXAQs3
heres the output from running the command

**Comment by YoJames2019** [comment]
The exact error is 

The Microsoft .NET Framework version 4.7.2 is not installed on this computer. Please run LogosSetup.exe to install the .NET Framework

**Comment by ferion11** [comment]
Please try using the `fast_install_AppImageWine_and_Logos.sh`, as there are still some bugs in both `wine` and `winetricks` that in some cases make this kind of error appear.

**Comment by jg00dman** [comment]
.NET installation is known to fail in wine sometimes due to a regression. The bug for this https://bugs.winehq.org/show_bug.cgi?id=48847
