### ISSUE TITLE
LogosCEF.exe Crashes with latest update

### ISSUE THREAD

**Issue by jaedog** [ferion11/LogosLinuxInstaller#200]
I updated both desktop and laptop and now get a crash for LogosCEF.exe on both. I did a clean install and have the same issue.

See below for details:

Unhandled exception: unimplemented function KERNEL32.dll.DiscardVirtualMemory called in 64-bit code (0x0000017002f998).
Register dump:
 rip:000000017002f998 rsp:000000000011efc0 rbp:0000000000248000 eflags:00000206 (   - --  I   - -P- )
 rax:0000000180000100 rbx:000000000011efe0 rcx:000000000011efe0 rdx:000000018b32ecf0
 rsi:0000000000001000 rdi:000071380024b000  r8:0000000181ea5931  r9:0000000000000000 r10:0000000000001800
 r11:000071380024b800 r12:0000713800448000 r13:0000713800200000 r14:0000000000001000 r15:0000000000000006
Stack dump:
0x0000000011efc0:  000000000011efe0 000000000011f030
0x0000000011efd0:  0000713800250e60 000000000011f680
0x0000000011efe0:  0000000180000100 0000000000000000
0x0000000011eff0:  000000017002f998 0000000100000002
0x0000000011f000:  000000018b333e22 000000018b32ecf0
0x0000000011f010:  0000000000000000 000000017002f0b4
0x0000000011f020:  0000000000000000 0000000000000000
0x0000000011f030:  0000000000000000 0000000000000000
0x0000000011f040:  000000018a548b50 aaaaaaaaaaaaaaaa
0x0000000011f050:  000000018b3cdc70 aaaaaaaa00000002
0x0000000011f060:  000000018a548b50 aaaaaaaaaaaaaaaa
0x0000000011f070:  000000018b385030 aaaaaaaa00000002
Backtrace:
=>0 0x0000017002f998 stub_entry_point+0x48(dll=<internal error>, name=<internal error>, ret_addr=<internal error>) [Z:\usr\src\packages\BUILD\dlls\ntdll\loader.c:359] in ntdll (0x00000000248000)
  1 0x00000181ea5931 in libcef (+0x1ea5931) (0x00000000248000)
  2 0x00000184199936 in libcef (+0x4199936) (0x00000000248000)
  3 0x00000184199579 in libcef (+0x4199579) (0x00000000000005)
  4 0x00000181e9df11 in libcef (+0x1e9df11) (0x000000409e0001)
  5 0x000001817ad2d7 in libcef (+0x17ad2d7) (0x00000000000001)
  6 0x000001815f3dfc in libcef (+0x15f3dfc) (0x00000000000001)
  7 0x000001815f291e in libcef (+0x15f291e) (0x00000000000001)
  8 0x000001802bf29d in libcef (+0x2bf29d) (0x00000000000001)
  9 0x000001802928b9 in libcef (+0x2928b9) (0x0000000011fca0)
  10 0x000001801f0792 in libcef (+0x1f0792) (0x0000000011fca0)
  11 0x0000014000af30 in logoscef (+0xaf30) (0x0000000011fca0)
  12 0x0000014000253e in logoscef (+0x253e) (0x0000000011fca0)
  13 0x00000140002821 in logoscef (+0x2821) (0000000000000000)
  14 0x00000140038eda in logoscef (+0x38eda) (0000000000000000)
  15 0x0000007b629679 BaseThreadInitThunk+0x9(unknown=<internal error>, entry=<internal error>, arg=<internal error>) [Z:\usr\src\packages\BUILD\dlls\kernel32\thread.c:61] in kernel32 (0000000000000000)
  16 0x00000170065343 __wine_pop_frame(entry=0000000140038F48, arg=0000000067FF0000) [Z:\usr\src\packages\BUILD\include\wine\exception.h:277] in ntdll (0000000000000000)
  17 0x00000170065343 RtlUserThreadStart+0x83(entry=[<register RSP not accessible in this frame>, arg=[<register RSP not accessible in this frame>) [Z:\usr\src\packages\BUILD\dlls\ntdll\thread.c:240] in ntdll (0000000000000000)
0x0000017002f998 stub_entry_point+0x48 [Z:\usr\src\packages\BUILD\dlls\ntdll\loader.c:359] in ntdll: jmp	0x0000017002f990 stub_entry_point+0x40
Unable to access file 'Z:\usr\src\packages\BUILD\dlls\ntdll\loader.c'
Modules:
Module	Address					Debug info	Name (67 modules)
PE	0000000000740000-00000000016b7000	Deferred        shell32
PE	00000000016c0000-0000000001c94000	Deferred        ole32
PE	0000000001ca0000-0000000001e67000	Deferred        winmm
PE	0000000001e70000-0000000001e9a000	Deferred        userenv
PE	0000000001ea0000-0000000001f52000	Deferred        secur32
PE	0000000001f60000-0000000001fad000	Deferred        jsproxy
PE	0000000001fb0000-0000000002121000	Deferred        chrome_elf
PE	0000000002130000-0000000002151000	Deferred        dwmapi
PE	0000000002160000-00000000024d9000	Deferred        urlmon
PE	00000000024e0000-0000000002790000	Deferred        comdlg32
PE	0000000002790000-00000000027e3000	Deferred        credui
PE	0000000003600000-000000000368a000	Deferred        winex11
PE	0000000010000000-0000000010002000	Deferred        usp10
PE	0000000061300000-0000000061391000	Deferred        iphlpapi
PE	0000000061540000-0000000061672000	Deferred        advapi32
PE	0000000061740000-00000000619c6000	Deferred        wininet
PE	0000000061d40000-0000000061de2000	Deferred        uiautomationcore
PE	0000000062cc0000-0000000062ce5000	Deferred        ncrypt
PE	0000000062dc0000-0000000063088000	Deferred        rpcrt4
PE	0000000063280000-00000000632a0000	Deferred        version
PE	00000000635c0000-00000000636e4000	Deferred        oleacc
PE	00000000639c0000-0000000063a15000	Deferred        shcore
PE	0000000064840000-0000000064997000	Deferred        shlwapi
PE	0000000064c00000-0000000064c17000	Deferred        esent
PE	0000000064cc0000-00000000651e9000	Deferred        oleaut32
PE	0000000065380000-00000000653af000	Deferred        wtsapi32
PE	0000000065d40000-0000000065d6b000	Deferred        kerberos
PE	0000000066040000-000000006608a000	Deferred        bcrypt
PE	00000000661c0000-00000000662bb000	Deferred        winspool
PE	00000000664c0000-00000000664f2000	Deferred        hid
PE	0000000066900000-0000000066954000	Deferred        win32u
PE	0000000067a80000-0000000067c2e000	Deferred        d3d9
PE	0000000068300000-00000000684a1000	Deferred        combase
PE	0000000068500000-00000000685cc000	Deferred        uxtheme
PE	00000000686c0000-0000000068762000	Deferred        netapi32
PE	0000000068c00000-0000000068c24000	Deferred        aclui
PE	0000000069400000-0000000069542000	Deferred        winhttp
PE	0000000069740000-00000000697cb000	Deferred        propsys
PE	0000000069e40000-0000000069eba000	Deferred        msacm32
PE	000000006a080000-000000006a3a8000	Deferred        msvcrt
PE	000000006abc0000-000000006ad1f000	Deferred        dxgi
PE	000000006b7c0000-000000006b7e1000	Deferred        dhcpcsvc
PE	000000006ba00000-000000006bad1000	Deferred        sechost
PE	000000006bc40000-000000006bf8c000	Deferred        dwrite
PE	000000006c540000-000000006c6cd000	Deferred        cryptui
PE	000000006c7c0000-000000006ca2c000	Deferred        gdi32
PE	000000006ca40000-000000006cf9e000	Deferred        comctl32
PE	000000006d580000-000000006d626000	Deferred        ws2_32
PE	000000006d680000-000000006d6c8000	Deferred        msv1_0
PE	000000006db80000-000000006db9e000	Deferred        wevtapi
PE	000000006e2c0000-000000006e30a000	Deferred        dnsapi
PE	000000006e6c0000-000000006ea42000	Deferred        crypt32
PE	000000006eb00000-000000006f100000	Deferred        user32
PE	000000006f280000-000000006f2a1000	Deferred        nsi
PE	000000006f2c0000-000000006f39d000	Deferred        wintrust
PE	000000006f880000-000000006fb7a000	Deferred        dbghelp
PE	0000000070740000-00000000707a8000	Deferred        mpr
PE	0000000070940000-0000000070a32000	Deferred        ucrtbase
PE	0000000071000000-0000000071061000	Deferred        imm32
PE	00000000710c0000-0000000071128000	Deferred        dxva2
PE	0000000071240000-0000000072853000	Deferred        wined3d
PE	000000007a850000-000000007a854000	Deferred        opengl32
PE	000000007b000000-000000007b5c3000	Deferred        kernelbase
PE	000000007b600000-000000007b79a000	Dwarf-4         kernel32
PE	0000000140000000-000000014007d000	Export          logoscef
PE	0000000170000000-000000017039d000	Dwarf-4         ntdll
PE	0000000180000000-000000018bd5c000	Export          libcef
Threads:
process  tid      prio    name (all IDs are in hex)
00000030 services.exe
	["C:\windows\system32\services.exe"]
	00000034    0     
	00000038    0     
	00000044    0     
	00000068    0     
	00000074    0     
	00000098    0     
	000000b0    0     
	000000dc    0     
0000003c winedevice.exe
	[C:\windows\system32\winedevice.exe]
	00000040    0     
	0000004c    0     
	00000050    0     
	00000054    0     
	00000058    0     
	0000005c    0     
	000000bc    0     
00000060 winedevice.exe
	[C:\windows\system32\winedevice.exe]
	00000064    0     
	0000006c    0     
	00000070    0     
	00000078    0     
	0000007c    0     
	00000080    0     
	00000084    0     
	00000088    0     
	0000008c    0     
00000090 plugplay.exe
	[C:\windows\system32\plugplay.exe]
	00000094    0     
	0000009c    0     
	000000a0    0     
	000000a4    0     
	00000228    0     
	00000654    0     
	00000658    0     
000000a8 svchost.exe
	[C:\windows\system32\svchost.exe -k LocalServiceNetworkRestricted]
	000000ac    0     
	000000b4    0     
	000000b8    0     
000000c0 explorer.exe
	["C:\windows\system32\explorer.exe" /desktop]
	000000c4    0     
	000000c8    0     
	000000cc    0     
000000d4 rpcss.exe
	[C:\windows\system32\rpcss.exe]
	000000d8    0     
	000000e4    0     
	000000e8    0     
	000000ec    0     
	000000f0    0     
	000000f4    0     
	00000474    0     
	000005dc    0     
000000fc conhost.exe
	["C:\windows\system32\conhost.exe" --unix --width 174 --height 35 --server 0x34]
	00000100    0     
00000410 LogosCEF.exe
	["C:\users\jae\AppData\Local\Logos\System\LogosCEF.exe" --type=gpu-process --no-sandbox --locales-dir-path="C:\users\jae\AppData\Local\Logos\System\CefLocales" --user-agent-product="Logos/28.0 (28.0.0.34; en-US; Win)" --lang=en-US --user-data-dir="C:\users\jae\AppData\Local\CEF\User Data" --custom-schemes=assembly|logos-app|logos-resource|https|themed|empty-request|dynamic-data --gpu-preferences=UAAAAAAAAADgAAAYAAAAAAAAAAAAAAAAAABgAAAAAAAwAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAGAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAACAAAAAAAAAA= --use-gl=disabled --log-file="C:\users\jae\AppData\Local\Faithlife\Logs\Logos\cef.log" --mojo-platform-channel-handle=4324 --field-trial-handle=4088,i,4458844315450764263,6989095400422212843,131072 --disable-features=WinUseBrowserSpellChecker /prefetch:2]
	00000414    0     
	0000042c    0     BrokerEvent
	00000438    0     
	0000051c    0     
00000424 LogosCEF.exe
	["C:\users\jae\AppData\Local\Logos\System\LogosCEF.exe" --type=utility --utility-sub-type=storage.mojom.StorageService --lang=en-US --service-sandbox-type=service --no-sandbox --locales-dir-path="C:\users\jae\AppData\Local\Logos\System\CefLocales" --user-agent-product="Logos/28.0 (28.0.0.34; en-US; Win)" --lang=en-US --user-data-dir="C:\users\jae\AppData\Local\CEF\User Data" --custom-schemes=assembly|logos-app|logos-resource|https|themed|empty-request|dynamic-data --log-file="C:\users\jae\AppData\Local\Faithlife\Logs\Logos\cef.log" --mojo-platform-channel-handle=4080 --field-trial-handle=4088,i,4458844315450764263,6989095400422212843,131072 --disable-features=WinUseBrowserSpellChecker /prefetch:8]
	00000428    0     
	00000460    0     BrokerEvent
	00000478    0     
	00000518    0     
00000430 winedbg.exe
	[winedbg --auto 1040 260]
	00000434    0     
00000440 explorer.exe
	["C:\windows\system32\explorer.exe" /desktop]
	00000444    0     
	0000046c    0     
	00000470    0     
00000464 winedbg.exe
	[winedbg --auto 1060 268]
	00000468    0     
0000052c conhost.exe
	["C:\windows\system32\conhost.exe" --unix --width 174 --height 35 --server 0x34]
	00000530    0     
0000053c Logos.exe
	["C:\users\jae\AppData\Local\Logos\System\Logos.exe"]
	00000540    0     
	00000544    0     
	00000548    0     
	0000054c    2     .NET Finalizer
	00000550    0     .NET Tiered Compilation Worker
	0000055c    0     
	00000564    0     .NET ThreadPool Wait
	00000568    0     
	00000570    0     .NET Timer
	00000574    0     .NET ThreadPool Worker
	00000578    0     .NET ThreadPool Gate
	0000057c    0     .NET ThreadPool Worker
	00000580    0     .NET ThreadPool Worker
	0000058c   -1     PreferencesManagerCore
	00000590    0     .NET BGC
	00000594    0     .NET ThreadPool Worker
	00000598    0     SynchronizationContextOperationManager
	0000059c    0     
	000005a0   -1     PreferencesManager
	000005a8    0     .NET ThreadPool IO
	000005ac    0     
	000005b0    0     .NET ThreadPool Worker
	000005b4   -1     LibraryCatalogResourceUse
	000005b8    0     SyncManager
	000005bc    0     CommunityClient
	000005c0    0     
	000005c4    0     
	000005c8    0     ResourceViewTracker
	000005cc   -1     LocalSqlCache
	000005d0    0     
	000005d4    0     
	000005d8    0     
	000005e4    0     .NET System Events
	000005e8    0     GlobalHotKeys
	000005ec    0     .NET ThreadPool Worker
	000005f4    0     .NET ThreadPool Worker
	000005f8    0     .NET ThreadPool Worker
	000005fc    0     .NET ThreadPool Worker
	00000600    0     .NET ThreadPool Worker
	00000604    0     .NET ThreadPool Worker
	00000608    0     CrBrowserMain
	0000060c    0     ThreadPoolServiceThread
	00000610    0     ThreadPoolForegroundWorker
	00000614   -2     ThreadPoolBackgroundWorker
	00000618    0     ThreadPoolForegroundWorker
	0000061c    0     ThreadPoolForegroundWorker
	00000620    0     Chrome_IOThread
	00000624    0     MemoryInfra
	00000628    0     
	0000062c    0     ThreadPoolSingleThreadCOMSTASharedForeground0
	00000630    0     ThreadPoolSingleThreadCOMSTASharedForegroundBlocking1
	00000634    0     CompositorTileWorker1
	00000638    0     ThreadPoolForegroundWorker
	0000063c    0     ThreadPoolForegroundWorker
	00000640    0     ThreadPoolSingleThreadForegroundBlocking2
	0000064c    0     
	00000650    0     VideoCaptureThread
	0000065c   -2     ThreadPoolSingleThreadSharedBackgroundBlocking3
	00000660    0     ThreadPoolSingleThreadSharedForegroundBlocking4
	00000664   -2     ThreadPoolBackgroundWorker
	00000670    0     ThreadPoolSingleThreadSharedForeground5
	0000067c    0     CacheThread_BlockFile
	00000694    0     UserEventManager
00000644 LogosCEF.exe
	["C:\users\jae\AppData\Local\Logos\System\LogosCEF.exe" --type=gpu-process --no-sandbox --locales-dir-path="C:\users\jae\AppData\Local\Logos\System\CefLocales" --user-agent-product="Logos/28.0 (28.0.0.34; en-US; Win)" --lang=en-US --user-data-dir="C:\users\jae\AppData\Local\CEF\User Data" --custom-schemes=assembly|logos-app|logos-resource|https|themed|empty-request|dynamic-data --gpu-preferences=UAAAAAAAAADgAAAYAAAAAAAAAAAAAAAAAABgAAAAAAAwAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAGAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAACAAAAAAAAAA= --use-gl=angle --use-angle=swiftshader-webgl --log-file="C:\users\jae\AppData\Local\Faithlife\Logs\Logos\cef.log" --mojo-platform-channel-handle=4092 --field-trial-handle=4096,i,16359578121826884991,1714853616792739277,131072 --disable-features=WinUseBrowserSpellChecker /prefetch:2]
	00000648    0     
	00000688    0     BrokerEvent
	00000698    0     
00000668 LogosCEF.exe
	["C:\users\jae\AppData\Local\Logos\System\LogosCEF.exe" --type=utility --utility-sub-type=storage.mojom.StorageService --lang=en-US --service-sandbox-type=service --no-sandbox --locales-dir-path="C:\users\jae\AppData\Local\Logos\System\CefLocales" --user-agent-product="Logos/28.0 (28.0.0.34; en-US; Win)" --lang=en-US --user-data-dir="C:\users\jae\AppData\Local\CEF\User Data" --custom-schemes=assembly|logos-app|logos-resource|https|themed|empty-request|dynamic-data --log-file="C:\users\jae\AppData\Local\Faithlife\Logs\Logos\cef.log" --mojo-platform-channel-handle=4232 --field-trial-handle=4096,i,16359578121826884991,1714853616792739277,131072 --disable-features=WinUseBrowserSpellChecker /prefetch:8]
	0000066c    0     
	0000069c    0     BrokerEvent
	000006a8    0     
00000674 (D) C:\users\jae\AppData\Local\Logos\System\LogosCEF.exe
	["C:\users\jae\AppData\Local\Logos\System\LogosCEF.exe" --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-US --service-sandbox-type=none --no-sandbox --locales-dir-path="C:\users\jae\AppData\Local\Logos\System\CefLocales" --user-agent-product="Logos/28.0 (28.0.0.34; en-US; Win)" --lang=en-US --user-data-dir="C:\users\jae\AppData\Local\CEF\User Data" --custom-schemes=assembly|logos-app|logos-resource|https|themed|empty-request|dynamic-data --log-file="C:\users\jae\AppData\Local\Faithlife\Logs\Logos\cef.log" --mojo-platform-channel-handle=4248 --field-trial-handle=4096,i,16359578121826884991,1714853616792739277,131072 --disable-features=WinUseBrowserSpellChecker /prefetch:8]
	00000678    0 <== 
	000006ac    0     BrokerEvent
	000006e4    0     
00000680 LogosCEF.exe
	["C:\users\jae\AppData\Local\Logos\System\LogosCEF.exe" --type=renderer --locales-dir-path="C:\users\jae\AppData\Local\Logos\System\CefLocales" --user-agent-product="Logos/28.0 (28.0.0.34; en-US; Win)" --uncaught-exception-stack-size=10 --user-data-dir="C:\users\jae\AppData\Local\CEF\User Data" --custom-schemes=assembly|logos-app|logos-resource|https|themed|empty-request|dynamic-data --first-renderer-process --no-sandbox --log-file="C:\users\jae\AppData\Local\Faithlife\Logs\Logos\cef.log" --disable-gpu-compositing --lang=en-US --device-scale-factor=1 --num-raster-threads=2 --enable-main-frame-before-activation --renderer-client-id=5 --time-ticks-at-unix-epoch=-1692658014316321 --launch-time-ticks=2388254064042 --mojo-platform-channel-handle=4384 --field-trial-handle=4096,i,16359578121826884991,1714853616792739277,131072 --disable-features=WinUseBrowserSpellChecker /prefetch:1]
	00000684    0     CrRendererMain
	000006bc    0     BrokerEvent
	000006c0    0     ThreadPoolServiceThread
	000006c4    0     ThreadPoolForegroundWorker
	000006c8   -2     ThreadPoolBackgroundWorker
	000006cc    1     Chrome_ChildIOThread
	000006d0    0     
	000006d4    0     
	000006d8    0     ThreadPoolForegroundWorker
	000006dc    0     GpuMemoryThread
	000006e0    0     ThreadPoolForegroundWorker
	000006e8    1     Compositor
	000006ec    0     ThreadPoolSingleThreadSharedForegroundBlocking0
	000006f0    0     CompositorTileWorker1
	000006f4    0     CompositorTileWorker2
	000006f8   -2     CompositorTileWorkerBackground
0000068c winedbg.exe
	[winedbg --auto 1604 264]
	00000690    0     
000006a0 winedbg.exe
	[winedbg --auto 1640 268]
	000006a4    0     
000006fc LogosIndexer.exe
	["C:\users\jae\AppData\Local\Logos\System\LogosIndexer.exe" /user:wlchvbiu.tb3 /lang:en-US]
	00000700    0     
	00000704    0     
	00000708    0     
	0000070c    2     .NET Finalizer
	00000710    0     .NET Tiered Compilation Worker
	00000718    0     .NET System Events
	0000071c    0     .NET ThreadPool IO
	00000720    0     .NET ThreadPool Wait
	00000724    0     .NET ThreadPool Worker
	00000728    0     .NET ThreadPool Gate
	0000072c    0     .NET ThreadPool Worker
	00000730   -2     UpdateLibraryCatalog
	00000734    0     .NET ThreadPool Worker
	00000738   -1     PreferencesManager
	0000073c   -1     LibraryCatalogResourceUse
	00000740   -1     PreferencesManagerCore
	00000744    0     .NET Timer
	00000748   -2     LibraryIndexer
	0000074c   -2     LibraryIndexer1
	00000750   -2     LibraryIndexer2
	00000754   -2     LibraryIndexer3
	00000758    0     .NET BGC
System information:
    Wine build: wine-7.18 (Staging)
    Platform: x86_64
    Version: Windows 10
    Host system: Linux
    Host version: 6.2.0-26-generic

**Comment by jaedog** [comment]
cef.log:

[0918/091742.465:ERROR:network_change_notifier_win.cc(221)] WSALookupServiceBegin failed with: 0
[0918/091742.558:WARNING:chrome_browser_cloud_management_controller.cc(87)] Could not create policy manager as CBCM is not enabled.
[0918/091800.665:ERROR:(-1)] Check failed: false. 
[0918/091800.684:ERROR:network_service_instance_impl.cc(541)] Network service crashed, restarting service.
[0918/091801.120:ERROR:(-1)] Check failed: false. 
[0918/091801.120:ERROR:gpu_process_host.cc(942)] GPU process exited unexpectedly: exit_code=-2147483392
[0918/091801.120:WARNING:gpu_process_host.cc(1292)] The GPU process has crashed 1 time(s)
[0918/091803.251:ERROR:(-1)] Check failed: false.

**Comment by thw26** [comment]
Thanks for reporting this. We believe it has to do with an update to Logos moving to version 28.0+ and using an old Wine version. Reports are that 8.15+ fixes the LogosCEF popups but 8.15+ are not as stable as 7.18+ with popups.

@jg00dman: any other thoughts here?

**Comment by jaedog** [comment]
What are the steps to try the updated wine-staging_8.14-x86_64.AppImage? I grabbed the appimage and moved it to the ./data/bin directory and updated the soft link. I get a ver mismatch error on launch.

**Comment by thw26** [comment]
You can find the latest AppImage at the following link:

https://github.com/mmtrt/WINE_AppImage/releases

It is a rolling release with no history; therefore we upload known good versions to this Github repo for the script's purposes.

Once you download the new version, you just need to update the AppImage's symlink named `selected_wine.AppImage` in the `LogosBible10/data/bin` dir to the new AppImage. You should be good to go after that.

You can also run `LogosBible10/Logos.sh -e` to edit the script's config file and update the AppImage file there to the new download. John Goodman says that this also successfully modifies the AppImage being used by the system. It is probably best to update both the symlink and the config file, as I was not aware during my programming that switching the config file's AppImage variable affected the launch script.

Otherwise, you would need to reinstall Logos once the wine staging binary has been installed to your system and use that binary during the install.

**Comment by Gene-W** [comment]
> Once you download the new version, you just need to update the AppImage's symlink named `selected_wine.AppImage` in the `LogosBible10/data/bin` dir to the new AppImage. You should be good to go after that.
> 

Thank you for this information. Editing the script's config file is pretty straight forward and easy, but I'm not familiar with updating the AppImage symlink. Searching hasn't been very fruitful, can you point me in the right direction to learn this one?

**Comment by thw26** [comment]
Closed with https://github.com/ferion11/LogosLinuxInstaller/commit/a794912d7efdae86c7dc381a060fe32f09a9d019
