### ISSUE TITLE
Crash Kde again

### ISSUE THREAD

**Issue by jg00dman** [ferion11/LogosLinuxInstaller#202]
Installing in gui mode, I clicked no to d3dcompiler install and it crashed the whole desktop session. 

Operating System: SteamOS 3.4.10
KDE Plasma Version: 5.26.1
KDE Frameworks Version: 5.99.0
Qt Version: 5.15.6
Kernel Version: 5.13.0-valve37-1-neptune (64-bit)
Graphics Platform: X11
Processors: 8 × AMD Custom APU 0405
Memory: 14.5 GiB of RAM
Graphics Processor: AMD Custom GPU 0405
Manufacturer: Valve
Product Name: Jupiter
System Version: 1

**Comment by jg00dman** [comment]
No terminal output because I launched it with double click to test this.

**Comment by thw26** [comment]
There should be terminal output here:

```
if [ -z "${LOGOS_LOG}" ]; then LOGOS_LOG="${HOME}/.local/state/Logos_on_Linux/install.log"; mkdir -p "${HOME}/.local/state/Logos_on_Linux"; touch "${LOGOS_LOG}"; export LOGOS_LOG; fi
```

I implemented this a while back for the other KDE crash.
