### ISSUE TITLE
Steam Deck requirements

### ISSUE THREAD

**Issue by jg00dman** [ferion11/LogosLinuxInstaller#203]
I'm using this to log and track steam deck install requirements. We've talked before about having the installer go ahead and offer to install dependencies. This is a dependency script for steam os. Based on a cups install script I found but cannot seem to find the source again.

[steam-os-dependencies.tar.gz](https://github.com/ferion11/LogosLinuxInstaller/files/12840079/steam-os-dependencies.tar.gz)

**Comment by jg00dman** [comment]
Need to add core-rel/libcurl-gnutls or you get a gnutls error.

**Comment by jg00dman** [comment]
Latest version: 
[steam-os-dependencies.tar.gz](https://github.com/ferion11/LogosLinuxInstaller/files/12840290/steam-os-dependencies.tar.gz)

**Comment by jg00dman** [comment]
Another update now handles locale issues.
[steam-os-dependencies.tar.gz](https://github.com/ferion11/LogosLinuxInstaller/files/12841689/steam-os-dependencies.tar.gz)

**Comment by jg00dman** [comment]
N.b. Steam OS updates can remove all these dependencies which is why a handy script is needed.

**Comment by thw26** [comment]
Do you think these are ready to be incorporated into the README?

**Comment by jg00dman** [comment]
[steam-os-dependencies.tar.gz](https://github.com/ferion11/LogosLinuxInstaller/files/13272139/steam-os-dependencies.tar.gz) I'm happy with this new version.

**Comment by thw26** [comment]
I've just pushed my initial changes to #193 based on the instructions you've provided. I just need your feedback on two things in Element to make sure I only execute these commands on SteamOS.
