### ISSUE TITLE
Logos crashing on load

### ISSUE THREAD

**Issue by jg00dman** [ferion11/LogosLinuxInstaller#205]
wine staging 8.17. 
Logos_v28.2.0.0043-x64.msi

https://bugs.winehq.org/show_bug.cgi?id=55743

[crash.txt](https://github.com/ferion11/LogosLinuxInstaller/files/12840282/crash.txt)

**Comment by thw26** [comment]
In recent conversation you said that 8.17 has been fairly stable. Has that proven to be true? What about 8.18?

**Comment by jg00dman** [comment]
Hard to be certain but I think this was caused by an intermittent internet connection. The exceptions don't get caught. Shouldn't be an issue from wine 8.19 onwards.
