### ISSUE TITLE
Fix Regressions in ControlPanel Template

### ISSUE THREAD

**Issue by thw26** [ferion11/LogosLinuxInstaller#207]
It seems that this update to the controlPanel template involved uploading a "completed" template. We need to revert those things which ruin the temple (e.g., removing backslashes before $s; variable names replaced with actual content).

https://github.com/ferion11/LogosLinuxInstaller/commit/032715f2ed38a26ba7be80fa0e525ab7302f1dbf

Further, it appears that this commit also enables some of the zenity only features by uncommenting; these need to be modified to have a CLI version.

Tagging @jg00dman since it was his commit.

**Comment by thw26** [comment]
On further review, it looks like you may have already corrected these things? Or at least most of them?

**Comment by jg00dman** [comment]
I've fixed the Launcher template I think. I can't see or understand where there is an issue with the control panel?  The diff doesn't show any slashes missing. Am I missing something or can we close this?

**Comment by thw26** [comment]
I've fixed these in some of my latest work. Closing.
