### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by arcanemuse** [ferion11/LogosLinuxInstaller#215]
Not sure why this is happening.  Both on a T430 and an X270 Thinkpad, Logos will install and then start.  It opens and then immediately crashes.  I installed  just fine on an Asus fliptop with a 6th gen processor and it works on that.  Something about Thinkpads that seems to cause it to crash.  I'm waiting for an SSD for my T480 to come in the mail so I can try it on that but I have a feeling it will do the same thing.  Has anyone else had issues with a Thinkpad?  If so, how did you resolve it?

**Comment by thw26** [comment]
This sounds like a known issue.

Try running:

`./Logos.sh --remove-library-catalog`

then try opening Logos again.

**Comment by arcanemuse** [comment]
I tried that with no effect.  I have also now tried it on a third computer.  This one is a desktop.  Also a bare metal install of Linux Mint.  Maybe it just hates Linux Mint?  I first tried it with the app image wine and then having zero luck with that, I used my own wine which is wine staging from wine hq.  I believe it is 8.2.  On the other laptop I tried uninstalling staging and installing dev and then uninstalled that and tried stable. None of those worked either.  Not sure why this won't run in Linux but I do have dual boots on most all of my machines with windoze on its own drive just in case.  There are a couple of things I have that flat won't run under wine like Accordance. I think version 10 was known to work at some point, but that is just too old, I need 14.

**Comment by thw26** [comment]
Okay. We've long seen it working on Ubuntu, and Mint is just an LTS Ubuntu, more or less. If you're getting to the install step, that generally would mean the script has done its job.

As long as your wine version is 7.19 staging or higher or 8.17 devel or higher, and as long as it is not version 8.0 on any branch, the wine version should be fine.

Are you using the latest development version of the script or [3.7.5](https://github.com/ferion11/LogosLinuxInstaller/releases/tag/v3.7.5)? There are some known regressions in the current development version which is why we haven't released an update yet.

If you can, run the install using 3.7.5.

Another possibility is that the launcher script could have a wrong setting. If you can, before running the script, set the following environment variable:

```
LAUNCHER_TEMPLATE_URL=https://github.com/ferion11/LogosLinuxInstaller/releases/download/v3.7.5/Launcher-Template.sh
```

**Comment by arcanemuse** [comment]
Maybe I'm doing it wrong but if I chmod +x that script and run it, I get this error. /Launcher-Template(1).sh: line 8: syntax error near unexpected token `('
./Launcher-Template(1).sh: line 8: `HERE="\$(dirname "\$(readlink -f "\${0}")")"'
And yes, I used the 3.75 script

**Comment by thw26** [comment]
Don't execute `Launcher-Template.sh`. Execute `LogosLinuxInstaller.sh` (LLI).

The Launcher-Template is populated during the execution of LLI.

**Comment by arcanemuse** [comment]
So where does the template go and how does it load?

**Comment by thw26** [comment]
The template is downloaded directly from the Internet from the URL dictated by the `LAUNCHER_TEMPLATE_URL` environment variable.

When it is downloaded, there is Bash black magic that populates the Launcher's environment variables.

There should be no need to download the launcher template. The only thing you should need to do is modify the URL for the launcher, as indicated in this post: https://github.com/ferion11/LogosLinuxInstaller/issues/215#issuecomment-1822939352

**Comment by arcanemuse** [comment]
This did not work either.  I think I am going to try using Tiny10 in Vmware.  I hate to use a virtual machine and use unlicensed win10 to make this work but I guess it is the only way.  This time it crashed while downloading resources and when attempting to open the program to continue the download, it immediately encountered a serious problem and crashed again.

**Comment by thw26** [comment]
We are currently rewriting the script in Python and hope to have a beta soon. This should resolve the issue with the launcher template, as the template is going away altogether.
