### ISSUE TITLE
Shell Install Crash

### ISSUE THREAD

**Issue by noticons** [ferion11/LogosLinuxInstaller#216]
After downloading the most recent LogosLinuxInstaller.sh, I made it executable then started it just to make sure it would run. It did. I then pressed cancel to exit the installer. It crashed and crashed the file manager I had open (the one executed it with).

Error read: Unknown product. Installation canceled!

**Comment by thw26** [comment]
This may be related to #202.

**Comment by thw26** [comment]
This would be the triggering code:

https://github.com/ferion11/LogosLinuxInstaller/blob/a794912d7efdae86c7dc381a060fe32f09a9d019/LogosLinuxInstaller.sh#L591-L592

By pressing cancel, the dialog would trigger the reported error, so this is expected.

This would be the error code itself where the process is killed:

https://github.com/ferion11/LogosLinuxInstaller/blob/a794912d7efdae86c7dc381a060fe32f09a9d019/LogosLinuxInstaller.sh#L238-L242

I am guessing something is going wrong here that is causing the crash.

**Comment by thw26** [comment]
With the Python rewrite incoming, this issue may not need further action.
