### ISSUE TITLE
New Logos Version (in app) Install crash

### ISSUE THREAD

**Issue by noticons** [ferion11/LogosLinuxInstaller#217]
I'm running wine-8.21 using native on the install of logos. Everything has been running well. The December iteration of the Logos program was released in the past few days, when it was pushed out, the Logos program tried to update itself and declared that it failed to install the application upgrade. 
I ran Logos from CLI, but never got any error messages whatsoever. This is a wine issue, I'm sure, but I just wanted to bring it up.

**Comment by noticons** [comment]
I tried running logos.sh with the -l flag in order to get the logs, and received this error:
./Logos.sh: line 423: [: DISABLED: integer expression expected
./Logos.sh: line 425: [: DISABLED: integer expression expected
LOGS var improperly set. Disabling Logos logs and resetting the LOGS value.
======= disable LogosBible logging only: =======
reg: The operation completed successfully
======= disable LogosBible logging done! =======

Looking at the script, the lines referenced are:
``				if [ "${LOGS}" -eq "DISABLED" ]; then
					logsOn;
				elif [ "${LOGS}" -eq "ENABLED" ]; then
					logsOff;
``

**Comment by thw26** [comment]
You can also run it from the CLI with no need for logs; you would just copy it from the terminal. I'd have to dig into the code to see why this is triggering.

**Comment by thw26** [comment]
Any other error code? Usually a crash hash a backtrace.

**Comment by noticons** [comment]
I also run Logos on linux on a separate computer, which is running it via the devel appimage (wine-devel_8.19-x86_64), and the same error occurs there.

**Comment by thw26** [comment]
This is related to the Logos 30+ update.

We have a partial fix but need more work to fix this one.

**Comment by noticons** [comment]
Great! Thanks so much. I'm glad the program performs so well for all the work that has gone into it from you guys.

**Comment by thw26** [comment]
See #219.
