### ISSUE TITLE
Add Logos 30.0+ Support

### ISSUE THREAD

**Issue by thw26** [ferion11/LogosLinuxInstaller#219]
FaithLife released an update in Logos 30.0 that requires new DLLs.

# STATUS

We are working on sorting this one out. We have an initial set of fixes but bumped into a secondary set of problems after the initial fix.

# WORKAROUND

Install the last version of 29 and disable auto-updates.

**Comment by eric-hansen** [comment]
How do we download v29 exactly?

**Comment by thw26** [comment]
At this point the easiest way will be to use the Python rewrite:

https://github.com/FaithLife-Community/LogosLinuxInstaller

The best would be to wait for us to release alpha3 due to issues in alpha2, but you can run from source (requires Python 3.12; instructions in README) and it should be fairly easy to do so.

**Comment by eric-hansen** [comment]
Cool, sounds good.  If the recommendation is to use said installer, should this repo be archived or at least the readme updated to reflect?

**Comment by thw26** [comment]
It will be archived in the near future once we are satisfied with the state of the new Python app. Since it is still alpha, I can't yet archive this. Please see the write up I made for the workaround here:

https://github.com/FaithLife-Community/LogosLinuxInstaller/wiki/Workaround-for-Logos-30-and-Higher-Using-the-Bash-Script

**Comment by jre95001** [comment]
Thank you!  That is a very helpful write-up!

Do you also have a URL to install the previous version of Verbum?

**Comment by thw26** [comment]
For Verbum, it should be a small modification. Here is the one-liner with no Zenity pop-ups:

```
LOGOS64_URL="https://downloads.logoscdn.com/LBS10/Verbum/Installer/29.1.0.0022/Verbum-x64.msi"
```

**Comment by noticons** [comment]
I'm sure this won't necessarily be helpful, but I just got the update to Wine 9.2 and the update still errors out. Thanks!

**Comment by JR1994** [comment]
I am still getting the same error as well. I know I set the variable

`[ricanlinux@archlinux LogosLinuxInstaller]$ echo $LOGOS64_URL
https://downloads.logoscdn.com/LBS10/Installer/29.1.0.0022/Logos-x64.msi
`

however it is still using the newer MSI

`Now the script will check for the MSI installer. Then it will download and install Logos Bible at /home/ricanlinux/LogosBible10/data/wine64_bottle. You will need to interact with the installer. Do you wish to continue? [Y/n]: y
Copying: Logos_v32.1.0.0031-x64.msi\ninto: /home/ricanlinux/LogosBible10/data
Copying: Launcher-Template.sh into /tmp/LBS.DcQgNz6l
Copying: controlPanel-Template.sh into /tmp/LBS.DcQgNz6l
Waiting for /home/ricanlinux/LogosBible10/data/bin/wine64 to end properly…
Waiting for /home/ricanlinux/LogosBible10/data/bin/wine64 to end properly…
Cleaning all temp files…
done
Installation failed.  not found. Exiting…\n\nThe Logos executable was not found. This means something went wrong while installing Logos. Please contact the Logos on Linux community for help.\n\nIf you need help, please consult:\n\nhttps://github.com/ferion11/LogosLinuxInstaller/wiki\nhttps://t.me/linux_logos\nhttps://matrix.to/#/#logosbible:matrix.org
Killed
`

**Comment by thw26** [comment]
Is that `echo` intentional?

Can you try running this instead before installing?

```
LOGOS64_URL=https://downloads.logoscdn.com/LBS10/Installer/29.1.0.0022/Logos-x64.msi
```

**Comment by JR1994** [comment]
that is what I did. The echo command validates that the variable has been set that is all.

**Comment by JR1994** [comment]
> 

Using you method got it install, but when the app starts the sync process it crashes with this error

![Screenshot from 2024-03-06 21-27-57](https://github.com/ferion11/LogosLinuxInstaller/assets/5367328/a88bb413-ea01-4194-a1d1-af68037fd474)

I can close and relaunch the app running the $HOME/LogosBible10/Logos.sh script

but gives the same crash when trying to sync and I cannot search my Library

**Comment by thw26** [comment]
We have started discussing that error here:

https://github.com/FaithLife-Community/LogosLinuxInstaller/issues/74

I think it is the lack of support for Logos 30+ that you're seeing here. Best bet is to disable automatic updates.

**Comment by noticons** [comment]
Be careful about upgrading Wine. I updated to wine 9.3. My logos installation wouldn't run after the upgrade. Thankfully, I was able to downgrade back to 9.2-1 and it ran perfectly

**Comment by thw26** [comment]
That's the first I've heard that a 9.x binary will work. Perhaps we can get an AppImage of it still.

**Comment by thw26** [comment]
We have released a new alpha version in the Python script that enables Logos 30+ access. It requires somewhere around at least Wine 9.10+ to run. Closing this issue.
