### ISSUE TITLE
script error installing dotnet 4

### ISSUE THREAD

**Issue by thiagoserra** [ferion11/LogosLinuxInstaller#22]
Hello all!
I was trying install Logos in my new computer with Ubuntu 20.04, but script fails when dot net setup start.
I try 3 times already and the error is the same.

![image](https://user-images.githubusercontent.com/3385403/103214752-b23e3a80-48e7-11eb-8947-7fafc0149b6d.png)

Detail of error on dot net setup:
Unhandled exception: C++ exception(object = 0x0031f594, type = 0x1009be00) in 32-bit code (0x7b00eb94).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:7b00eb94 ESP:0031f4a4 EBP:0031f508 EFLAGS:00000246(   - --  I  Z- -P- )
 EAX:0031f4b0 EBX:0031f594 ECX:00000008 EDX:0031f534
 ESI:100187cc EDI:00000000
Stack dump:
0x0031f4a4:  00bb5ee8 0031f4e8 7bc7846c e06d7363
0x0031f4b4:  00000001 00000000 7b00eb94 00000003
0x0031f4c4:  19930520 0031f594 1009be00 00cf1c58
0x0031f4d4:  0031f4e8 0031f500 00110000 00000000
0x0031f4e4:  00000000 0031f528 7bc79f45 1005ed5e
0x0031f4f4:  1005ed63 0031f528 7bc79f45 00110000
Backtrace:
=>0 0x7b00eb94 RaiseException+0x6f(code=<is not available>, flags=<is not available>, count=<is not available>, args=<is not available>) [Z:\home\runner\work\f11_wine64_builder\f11_wine64_builder\build32\dlls\kernelbase\..\..\..\wine-src\dlls\kernelbase\debug.c:333] in kernelbase (0x0031f508)
  1 0x100814f2 in setupengine (+0x814f1) (0x0031f540)
  2 0x10066a29 EntryPoint+0xffffffff() in setupengine (0x0031f5b0)
  3 0x100636d8 EntryPoint+0xffffffff() in setupengine (0x0031f5d0)
  4 0x10061338 EntryPoint+0xffffffff() in setupengine (0x0031f608)
  5 0x10035a14 EntryPoint+0xffffffff() in setupengine (0x0031f678)
  6 0x1006b498 EntryPoint+0xffffffff() in setupengine (0x0031fdd8)
  7 0x1005fa6e EntryPoint+0xffffffff() in setupengine (0x0031fe48)
  8 0x10058323 EntryPoint+0xffffffff() in setupengine (0x0031fe9c)
  9 0x00402928 EntryPoint+0xffffffff() in setup (0x0031ff30)
  10 0x7b64bd61 in kernel32 (+0x2bd60) (0x0031ff48)
  11 0x7b64c414 in kernel32 (+0x2c413) (0x0031ffd8)
  12 0x7b64bd72 in kernel32 (+0x2bd71) (0x0031ffec)
0x7b00eb94 RaiseException+0x6f [Z:\home\runner\work\f11_wine64_builder\f11_wine64_builder\build32\dlls\kernelbase\..\..\..\wine-src\dlls\kernelbase\debug.c:333] in kernelbase: movl	0xfffffffc(%ebp),%ebx
Unable to access file 'Z:\home\runner\work\f11_wine64_builder\f11_wine64_builder\build32\dlls\kernelbase\..\..\..\wine-src\dlls\kernelbase\debug.c'
Modules:
Module	Address			Debug info	Name (50 modules)
PE	  320000-  33e000	Deferred        aclui
PE	  340000-  3b5000	Deferred        wintrust
PE	  400000-  415000	Export          setup
PE	  420000-  62b000	Deferred        urlmon
PE	  630000-  671000	Deferred        jsproxy
PE	10000000-100c8000	Export          setupengine
PE	61b00000-61b70000	Deferred        sechost
PE	61f00000-61f31000	Deferred        sxs
PE	62780000-627a3000	Deferred        mspatcha
PE	62800000-6289c000	Deferred        usp10
PE	62940000-62968000	Deferred        imagehlp
PE	64540000-645fb000	Deferred        winhttp
PE	64b40000-64b72000	Deferred        shcore
PE	65200000-655ff000	Deferred        ole32
PE	65980000-65997000	Deferred        version
PE	66400000-665ba000	Deferred        dbghelp
PE	67f00000-67f1d000	Deferred        userenv
PE	68c40000-68d29000	Deferred        shlwapi
PE	6a300000-6a5d9000	Deferred        oleaut32
PE	6a900000-6aa4b000	Deferred        setupapi
PE	6aec0000-6aecf000	Deferred        psapi
PE	6b4c0000-6b60d000	Deferred        wininet
PE	6c0c0000-6c0f3000	Deferred        imm32
PE	6cd00000-6cd24000	Deferred        sqmapi
PE	6dbc0000-6dc00000	Deferred        mpr
PE	6e1c0000-6e204000	Deferred        cabinet
PE	6e8c0000-6ebbb000	Deferred        comctl32
PE	6f280000-6f2ad000	Deferred        odbccp32
PE	6fdc0000-6ff4d000	Deferred        rpcrt4
PE	71400000-71875000	Deferred        msi
PE	7b000000-7b262000	Dwarf           kernelbase
PE	7b620000-7b7f1000	Export          kernel32
PE	7bc30000-7bc48000	Deferred        ntdll
PE	7d3d0000-7d3d4000	Deferred        kerberos
PE	7d3f0000-7d3f6000	Deferred        uxtheme
PE	7d730000-7d735000	Deferred        winex11
PE	7d800000-7d815000	Deferred        msvcrt
PE	7d8f0000-7d8f7000	Deferred        dnsapi
PE	7d910000-7d917000	Deferred        iphlpapi
PE	7d950000-7d958000	Deferred        netapi32
PE	7d990000-7d995000	Deferred        secur32
PE	7d9d0000-7d9d7000	Deferred        ws2_32
PE	7da10000-7da16000	Deferred        bcrypt
PE	7da50000-7da98000	Deferred        crypt32
PE	7db50000-7e44c000	Deferred        shell32
PE	7e580000-7e58e000	Deferred        gdi32
PE	7e6e0000-7e7d4000	Deferred        user32
PE	7e920000-7e948000	Deferred        ucrtbase
PE	7ea10000-7ea1d000	Deferred        advapi32
PE	7eff0000-7eff3000	Deferred        wow64cpu
Threads:
process  tid      prio (all id:s are in hex)
00000020 dotNetFx40_Full_x86_x64.exe
	["Y:\dotnet40\dotNetFx40_Full_x86_x64.exe"]
	00000024    0
00000038 services.exe
	00000098    0
	0000006c    0
	0000004c    0
	00000040    0
	0000003c    0
00000044 plugplay.exe
	0000007c    0
	00000060    0
	0000005c    0
	00000058    0
	00000048    0
00000064 winedevice.exe
	0000008c    0
	00000088    0
	00000078    0
	00000074    0
	00000070    0
	00000068    0
00000090 winedevice.exe
	000000a4    0
	000000a0    0
	0000009c    0
	00000094    0
000000a8 explorer.exe
	000000b8    0
	000000b4    0
	000000b0    0
	000000ac    0
000000cc (D) C:\b38ca6485aa241b529cef2c2\Setup.exe
	[C:\b38ca6485aa241b529cef2c2\\Setup.exe   /x86 /x64]
	000000dc    0
	000000d0    0 <==
000000e0 explorer.exe
	000000f0    0
	000000ec    0
	000000e8    0
	000000e4    0
System information:
    Wine build: wine-5.11 (Staging)
    Platform: i386 (WOW64)
    Version: Windows XP
    Host system: Linux
    Host version: 5.4.0-58-generic
`
`

**Comment by ferion11** [comment]
Please try using the `fast_install_AppImageWine_and_Logos.sh` instead of `install_AppImageWine_and_Logos.sh`.

**Comment by thiagoserra** [comment]
The installation finish with de fast script.
however, after literally eating up the machine's memory for 2:43h by indexing the library, Logos is now not consistent.
If I open any book with another one next to it, it just closes.
sometimes just using the Bible or making use of a book it just closes and starts indexing again ... any tips?
by the way, thanks a lot for your work!!
 
![2020-12-29_17-14](https://user-images.githubusercontent.com/3385403/103351165-b2217480-4a78-11eb-8a15-c4650ec9d63e.png)

**Comment by ferion11** [comment]
> The installation finish with de fast script.
> however, after literally eating up the machine's memory for 2:43h by indexing the library, Logos is now not consistent.
> If I open any book with another one next to it, it just closes.
> sometimes just using the Bible or making use of a book it just closes and starts indexing again ... any tips?
> by the way, thanks a lot for your work!!
> 
> ![2020-12-29_17-14](https://user-images.githubusercontent.com/3385403/103351165-b2217480-4a78-11eb-8a15-c4650ec9d63e.png)

If the `LogosIndexer.exe` process is there, then the indexing still have job to be done. There is one report of the indexing needing more RAM memory than the last version, so you should close the LogosBible, and others apps while it (LogosIndexer.exe) still there.

If you want, you can kill all process using:
```
$ /Logos.sh wineserver -k
```

Then, you can re-start the indexing without the LogosBible with:
```
$ ./Logos.sh indexing
```

And if you want clean all bugged index, then you can, before the indexing, do:
```
$ ./Logos.sh removeAllIndex
then
$ ./Logos.sh indexing
```
It's best to do this at night, or at another time when you aren't using the machine (leaving all the RAM memory for the indexing process).
