### ISSUE TITLE
Install Failed: Logos Bible Study requires Windows to be fully updated

### ISSUE THREAD

**Issue by JR1994** [ferion11/LogosLinuxInstaller#224]
When I try to install the wine app image and native wine I get the titled message. I am attaching a screenshot of the error

![Screenshot from 2024-02-29 18-10-25](https://github.com/ferion11/LogosLinuxInstaller/assets/5367328/f52be17a-c115-46a6-b6be-8d660cea3191)

System
ArchLinux
Intel Xeon X5675 (12) @ 3.060GHz
24 GB RAM
Radeon Vega 64

**Comment by andyhunne** [comment]
Here is a workaround:
https://github.com/FaithLife-Community/LogosLinuxInstaller/wiki/Workaround-for-Logos-30-and-Higher-Using-the-Bash-Script

It's this issue here: https://github.com/ferion11/LogosLinuxInstaller/issues/219

**Comment by thw26** [comment]
Duplicate of #219 .
