### ISSUE TITLE
Arch Compatability

### ISSUE THREAD

**Issue by Mertzenich** [ferion11/LogosLinuxInstaller#27]
Compatability for Arch based distributions would be appreciated.

**Comment by ferion11** [comment]
The Archlinux is having several issues because it's using glibc v2.33, which has proved problematic in many linux distributions.

**Comment by Mertzenich** [comment]
I am not sure if it was an update to any of my packages in the arch repositories or if a change was made to the installer script but it now installs perfectly fine on my system.
