### ISSUE TITLE
Allow people to choose between Logos or Verbum

### ISSUE THREAD

**Issue by Mertzenich** [ferion11/LogosLinuxInstaller#28]
Logos and Verbum are essentially the same, not sure if there are other changes besides branding. It would be nice if the tool let you choose to install one or the other.

**Comment by ferion11** [comment]
I think the app is exactly the same, and when you subscribe to Verbum, it's normally available on LogosBible. I had done this test on LogosBible 8. But I would also like to know if the Verbum installer includes any different features.

**Comment by jg00dman** [comment]
I sent you a pull request for a Verbum install script. It is a different app, in particular it handles apocrypha differently.

**Comment by ferion11** [comment]
Sorry, I haven't reviewed this yet. I'll check it out later.

**Comment by jg00dman** [comment]
It's a more complex thing to do than one might at first think. Verbum uses the word 'Logos' in its registry settings etc. For the most part I created the script by find/replace. But I also had to carefully select where not to change it. Also the icon for the shortcut etc.

**Comment by thw26** [comment]
With @jg00dman's new Logos 10 install scripts, we can eventually do a more careful consideration of how to combine the two scripts.
