### ISSUE TITLE
Slow and hanging

### ISSUE THREAD

**Issue by clschwab216** [ferion11/LogosLinuxInstaller#30]
This is fantastic to have back on my Ubuntu box! I finally got it installed using the native install. Here are the issues:

1. When I try to open a passage study layout, it hangs (not responding, wait or force quit, you get the idea). Leaving it go for several minutes finally has it pulling up the PSL, but I still have a spinning wheel as it thinks really hard about this.
2. I needed to do a diagram, so I loaded the diagramming module. This runs but is very slow and laggy.

When I had the 32-bit of Logos 8 using wasta, it ran very quickly, though over time I developed errors that made it unusable. Running:

- Ubuntu 20.04.2 LTS
- Ryzen 3 2200g
- Asrock Radeon RX 5500 XT w/ 8 GB RAM
- 16 GB RAM
- 500 GB M2 SSD

So I don't think it's an issue of specs. But it's almost like Logos doesn't have access to the full resources of the computer. 

Indexing is complete, so it's not a matter of that background process slowing things down either. Any thoughts? Can I find any logs anyplace that would help?

UPDATE: Looking at the PSL, I tried to click on categories of commentaries and everything crashed. Process over.

**Comment by jg00dman** [comment]
This was a regression which got fixed in time for wine 7

**Comment by clschwab216** [comment]
I don't really understand your comment, I apologize. I'm not a Linux expert by any stretch. But here's an update: 

I've done a fresh install of my entire system with Pop_OS! 20.04. I was able to install Logos just fine, and I've had no crashes, but the program runs crazy slow. For instance, clicking from one open translation tab to another open translation tab takes 5-7 seconds. Clicking the Docs menu takes about 2 seconds to respond and about 8 seconds to fully load. Trying to add a new tab, just to open another translation, gives me a "WINE is not responding." After a couple of those and about 30 seconds, it starts loading the add pane.

So if this is a fresh install of the OS and of Logos and I'm getting similar issues--albeit without a full crash yet--something else must be going on.
