### ISSUE TITLE
Trying to install needed dependencies...

### ISSUE THREAD

**Issue by benbrockn** [ferion11/LogosLinuxInstaller#33]
So, I already installed these programs using `yay` to fix these errors:
`xorg-xwd` for "xwd"
`cabextract` for "cabextract"

but I can't seem to figure out "ntlm_auth"

I installed `python-ntlm-auth`, which didn't work, so I also installed `python-ntml3` (python 3) which also didn't work. So I then installed `python2-ntml3` (python 2) which removed the python 3 version, but that didn't work either. So then I tried the `perl-ntlm` package and that didn't work either.

What am I supposed to install??

**Comment by ferion11** [comment]
There are many package names that contain this utility (different in each linux distribution), the best known is perhaps `winbind`. But if this isn't your case, please tell us which linux distribution is in use.

**Comment by benbrockn** [comment]
I use EndeavourOS which is an arch-based distro like Manjaro. I searched for `winbind` using `yay`, but nothing came up:

```
yay winbind
no packages match search
```

**Comment by ferion11** [comment]
On arch-based distro, the package is `samba`.

**Comment by benbrockn** [comment]
`samba` worked, though I hate using SMB. After install I'm deleting these packages, so we'll see if it works without them.

**Comment by benbrockn** [comment]
Well, it either didn't work after install or it doesn't like uninstalling `xorg-xwd`, `cabextract`, and `samba`.

Either way, I'll probably have to reinstall because my home directory has only 10GB left and Logos 9 with all my resources is like 13+GB. So... my bad. I'll try again later. Can I install it on a different internal or external drive?

**Comment by ferion11** [comment]
> Can I install it on a different internal or external drive?

Yes. Just set the INSTALLDIR variable, like:
```
$ INSTALLDIR=/media/sdc1/LogosBible_Linux_P ./fast_install_AppImageWine_and_Logos.sh
```

**Comment by Mertzenich** [comment]
Here is a list of arch packages, from the official repositories, that I installed to get the script to run. There may be others not listed that I already had installed. Might be worth adding a dependency list for different distributions?

`Zenity cabextract samba libjpeg-turbo wget xorg-xwd`
