### ISSUE TITLE
Cannot Open Links

### ISSUE THREAD

**Issue by john-okeefe** [ferion11/LogosLinuxInstaller#34]
I'm using Arch with Plasma Desktop and the AppImage with Deps version instead of local. Logos crashed with local and runs with your appimage WINE.

However, when I try to open links I get the error below.

kde-open5: /tmp/.mount_wine64aN6Q40/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/libKF5KIOCore.so.5

Apparently the the libstdc++.so.6 you are using stops at GLIBCXX_3.4.28.

strings libstdc++.so.6 | grep GLIBCXX 
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
GLIBCXX_DEBUG_MESSAGE_LENGTH

**Comment by ferion11** [comment]
Sorry, but the AppImage version is unstable. LogosBible requires an AppImage that includes both 64bit and 32bit dependencies toguether, but unfortunately so far nobody has created an AppImage that meets these characteristics.

**Comment by jg00dman** [comment]
There was a regression in wine which affect all opening of links in various apps not just Logos. We got it fixed in time for wine 7.
