### ISSUE TITLE
Combine Scripts into a Single Install Script and a Single Run Script

### ISSUE THREAD

**Issue by thw26** [ferion11/LogosLinuxInstaller#36]
Do we need both a standard and fast script, or could the fast script function as an option in the main script, or vice versa?

After working on making the script CLI friendly, I'd like to combine them at some point for easier maintenance and not needing to duplicate work.

**Comment by ferion11** [comment]
The script `fast_install_AppImageWine_and_Logos.sh` is just a workaround. But at the moment, because of bugs in the WINE installation, that's what's working. Unfortunately, I don't have time to unify the two in a easy way (and the workaround should be the default until the other way start to work again).

**Comment by thw26** [comment]
I'm also thinking that the controlPanel.sh script could be combined with Logos.sh as I am looking over it.

I'm not so much asking for this as I am making a note of it for future work.

**Comment by ferion11** [comment]
> I'm also thinking that the controlPanel.sh script could be combined with Logos.sh as I am looking over it.
> 
> I'm not so much asking for this as I am making a note of it for future work.
> 
> I'm thinking in general having a Logos_Install.sh script and a Logos_Run.sh script, as basic examples.

I think the `all in one file` approach isn't very good in this case. I tried to separate WINE-related things into `controlPanel.sh` and LogosBible-related things in `Logos.sh`.

**Comment by thw26** [comment]
> I think the `all in one file` approach isn't very good in this case. I tried to separate WINE-related things into `controlPanel.sh` and LogosBible-related things in `Logos.sh`.

Copy that.
