### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by phix8** [ferion11/LogosLinuxInstaller#37]
```
line 7: syntax error near unexpected token `newline'
line 7: `<!DOCTYPE html>'
```

Installing on Garuda KDE via Konsole using the following command in the Downloads folder:
./fast_install_AppImageWine_and_Logos.sh

**Comment by ferion11** [comment]
You downloaded the blob version, that's only for better display the code, the git link should have raw on the name, like:
https://raw.githubusercontent.com/ferion11/LogosLinuxInstaller/master/fast_install_AppImageWine_and_Logos.sh

The last version is on the release page too:
https://github.com/ferion11/LogosLinuxInstaller/releases
https://github.com/ferion11/LogosLinuxInstaller/releases/download/v2.33/fast_install_AppImageWine_and_Logos.sh

**Comment by phix8** [comment]
Thanks! I tried running it on Garuda KDE (an Arch distro) and it is telling me:
Your system does not have the command: xwd. Please install command xwd package. Usually is necessary: winbind cabextract libjpeg8.

I assume that this script is for Debian distros only? I tried installing Samba (which I read contains winbind) but I'm still getting that error. I'm a newb at this, so I'm not even sure how to install these packages on Garuda. All the documentation out there is for Ubuntu.

**Comment by ferion11** [comment]
On Arch based distro, the xwd package name is: xorg-xwd

**Comment by phix8** [comment]
Thank you! That worked and I've successfully installed Logos. I'm downloading my resources now.
