### ISSUE TITLE
Missing Dependency: libgjpeg.so.62

### ISSUE THREAD

**Issue by thw26** [ferion11/LogosLinuxInstaller#39]
I got this error today on Manjaro.

```03bc:err:wincodecs:jpeg_decoder_create Failed reading JPEG because unable to find libjpeg.so.62
```

It caused Logos to crash, stating that there was an error with LogosCEF.exe. I fixed this by installing the `libjpeg6-turbo` package and this resolved the issue. I see the `check_libs` function is currently commented out. We may want to add this as a dependency.

**Comment by thw26** [comment]
What about including an install function that checks for an Arch distribution and reports it? Then only users who run Arch or derivatives would see the message? Obviously we can't anticipate every variation of every distribution, but Arch and Manjaro are probably the most popular in that family.

This is probably a decent way to check:

```
if [ -f "/etc/arch-release" ]; then
  ...
else
  ...
fi
```

**Comment by ferion11** [comment]
Things related to linux distributions should be left to the respective distributions to solve.
In the case of ArchLinux, I believe the package should be recompiled with a link to libjpeg.so.8 from the libjpeg-turbo package (libjpeg6-turbo would be unnecessary).

**Comment by thw26** [comment]
Understood.
