### ISSUE TITLE
Add Binary Path Variable to Generated Scripts

### ISSUE THREAD

**Issue by thw26** [ferion11/LogosLinuxInstaller#41]
I've been using PlayOnLinux to have multiple wine versions for testing purposes, and also to go back when Arch updates its wine version. This requires editing the Logos.sh and controlPanel.sh script to adjust the binary paths for calling `wine64` and `wineserver`. Adding a variable that can be adjusted would save a couple minutes of time when testing.

Again, not requesting you to work on this @ferion11, but making a note for myself.

**Comment by ferion11** [comment]
In `Logos.sh` and `controlPanel.sh`, it has no code to switch between WINE installations. But I created one fake AppImage for this purpose:
Code: https://github.com/ferion11/libsutil/blob/master/shell_scripts/wine-fake.AppImage
Download: https://github.com/ferion11/libsutil/releases/tag/fakeAppImage

Put the `wine-fake.AppImage` into the directory `LogosBible64_Linux_P/data/`, then run:
```
$ chmod +x wine-fake.AppImage
$ ./wine-fake.AppImage selectInstallation
```
After set the installation, then go back to the directory `LogosBible64_Linux_P`, and run:
```
$ ./controlPanel.sh selectAppImage
```
and select the `wine-fake.AppImage`

This approach is better than inserting extra code into the execution scripts.

**Comment by ferion11** [comment]
> I personally have always edited the scripts to have a path variable for wine and wineserver. I didn't realise you had such an elegant solution. May I ask, could we take it one step further and when you choose to select app image, suppose you have a choice to give it the path to a dir instead of an appImage? Then the script goes ahead and configures the fake app image... I feel this would be more user friendly.

If you run the [wine-fake.AppImage](https://github.com/ferion11/libsutil/blob/master/shell_scripts/wine-fake.AppImage), then it will ask for a dir of the WINE installation. But I think it isn't that easy to use.
I'm thinking of a more user-friendly approach to the problem.
But I want an approach with little code change, perhaps resetting the script's `$PATH` if the `$LOGOS_WINE_BIN_PATH` variable is set.
