### ISSUE TITLE
Re-create shortcut after installing new distro

### ISSUE THREAD

**Issue by Gene-W** [ferion11/LogosLinuxInstaller#48]
I would like to re-create the shortcut that could appear in the app drawer or on the desktop after changing distros. There was no need for me to re-install Logos since /home is on it's own drive, but following the steps to create shortcut don't appear to work, or what's more likely is that I'm not certain how to pick up from that point and create the shortcut. :)

**Comment by ferion11** [comment]
Hi!
To re-create the shortcut, use:
```
$ ./Logos.sh shortcut
```
It will create the `LogosBible.desktop` inside your `${HOME}/.local/share/applications`, that can be edited.

**Comment by Gene-W** [comment]
That was simple, thank you!
