### ISSUE TITLE
Logos 9.10 has menu issues

### ISSUE THREAD

**Issue by jg00dman** [ferion11/LogosLinuxInstaller#49]
Owing to a change in Logos, from 9.10 onwards there are glitches in the docs, tools and guides menus. After first click they need to be double clicked to show. I suggest keeping Logos 9.9 as the version installed by the script. So long as wine is set to win7, updates won't happen from the app itself. Once we get the glitches fixed then maybe have the script updated to Logos 9.10.

**Comment by ferion11** [comment]
Thanks
