### ISSUE TITLE
LMDE4 errors installing Logos

### ISSUE THREAD

**Issue by osmelgithub** [ferion11/LogosLinuxInstaller#5]
I downloaded and try to install logos appimage but it fails in create the .wine32 folder

**Comment by ferion11** [comment]
Could you tell me what you have done? Step by step. And what is the error message?
NOTE: You should execute the `$HOME/Desktop/Logos.sh`script and not the Desktop shortcut (that maybe wine auto-create).

**Comment by ferion11** [comment]
If you are still experiencing this issue, feel free to reopen this issue https://github.com/ferion11/LogosLinuxInstaller/issues/5.
