### ISSUE TITLE
Layouts not working properly

### ISSUE THREAD

**Issue by Ratramnus** [ferion11/LogosLinuxInstaller#50]
I've noticed in the last few weeks that the Layouts button (on the top right) in Logos now doesn't seem to work properly. I can use it once when I first start up Logos. But after the first use, I can't get the button to present the options. There is simply a flicker of the window and nothing.

I've installed Logos using the LogosLinuxInstaller script on a suite of distros (Mint 20.3, Ubuntu 20.04, Latest Manjaro KDE and Manjaro GNOME, Fedora) on several different machines, and they all present the same problem.

Anyone else experiencing this as well?

**Comment by ferion11** [comment]
Most likely it is related to: https://github.com/ferion11/LogosLinuxInstaller/issues/49

**Comment by Ratramnus** [comment]
Thanks for the tip. Helpful.
