### ISSUE TITLE
Distro-specific issues

### ISSUE THREAD

**Issue by Ulrik-dk** [ferion11/LogosLinuxInstaller#54]
Observation: It seems, from the Logos forum, and from my own experiences, that Manjaro specifically has some issues with making it work. The same procedure that, I assume, works for most, doesn't seem to work on Manjaro.

Request: Can we have a list of distros, on which this is confirmed to work? Different distros have different versions of dependencies available, so it should be no surprise that some work while others don't.

**Comment by ferion11** [comment]
I don't think the problem is with the manjaro itself.
With `fast_install_AppImageWine_and_Logos.sh`, the main dependency is WINE. So if WINE is working normally, the script should be able to install LogosBible.

**Comment by thw26** [comment]
If you do find a distro specific issue, please include a write-up here:

https://github.com/ferion11/LogosLinuxInstaller/wiki#distro-specific-issues

**Comment by Ulrik-dk** [comment]
Okay but, I recapitulate my request: Request: Can ~~we~~ I have a list of distros, on which this is confirmed to work? Just one or two.

**Comment by thw26** [comment]
> Okay but, I recapitulate my request: Request: Can ~we~ I have a list of distros, on which this is confirmed to work? Just one or two.

The short answer is any distro with Wine >7.0. Two example distros I know to be in use are Ubuntu and Manjaro. I personally use Manjaro.
