### ISSUE TITLE
We can speed up the corefonts installation significantly

### ISSUE THREAD

**Issue by jg00dman** [ferion11/LogosLinuxInstaller#55]
https://www.reddit.com/r/SteamPlay/comments/9g6ytd/foss_corefonts_if_your_game_needs_corefonts_to/
My understanding is that Proton now uses this by default. I wonder if we could use the modified winetricks?

**Comment by ferion11** [comment]
Thanks.
I will analyze compatibility with the dotnet installation first.
But it looks promising.
