### ISSUE TITLE
Bottles Integration

### ISSUE THREAD

**Issue by noticons** [ferion11/LogosLinuxInstaller#57]
Would it be possible to create a bottles integration to make it easier for normal folks? 
Bottles is a Wine front end with sandboxing that can use installation scripts--in the yml format.
It's currently available, cross platform, as a flatpak (Flathub repo).
It would be nice, as it might make the process more approachable and automated.
Example video:
https://youtu.be/gpsmHI7oPas
Specifically:
https://www.youtube.com/watch?v=gpsmHI7oPas&t=306s

**Comment by ferion11** [comment]
The issue here with `LogosBible` is the successful installation of `DotNet 4.8`.
If the application `Bottles` can install the `DotNet 4.8`, the it also can install `LogosBible` directly, without the need of this script.

**Comment by thw26** [comment]
With Logos 10 we no longer need to install DotNet manually. If one of our Bottles users can help with anything special, then we can look at adding an install option alongside the main options.

**Comment by noticons** [comment]
Does that mean that DotNet is optional? I looked through the system requirements and didn't see .net dependency, but when I looked through "what's new" I found this:
"Logos 10 Is Lightning Fast Including Support for .NET 6 and Apple Silicon"
Perhaps I'm misunderstanding what you are saying. I would be so glad, of course, if version 10 was more agnostic about it's support base.

**Comment by noticons** [comment]
That sounds good... I hope it is good, lol. It certainly simplifies the process.

**Comment by jg00dman** [comment]
It will need to be more of a bottles port... the installer has to be in yml but the Logos.sh and config scripts could be reused. I've started [bottle installer github repos](https://github.com/jg00dman/programs)

**Comment by sweenu** [comment]
> It will need to be more of a bottles port... the installer has to be in yml but the Logos.sh and config scripts could be reused. I've started [bottle installer github repos](https://github.com/jg00dman/programs)

@jg00dman In your fork I don't see Logos added. Where did you add your changes?

**Comment by thw26** [comment]
You can also talk with Adam York in Telegram or Matrix, as he is the most avid Bottles user.
