### ISSUE TITLE
Logos 10 Support

### ISSUE THREAD

**Issue by jg00dman** [ferion11/LogosLinuxInstaller#58]
See details in the forum, on winehq or in my [release notes.
](https://docs.google.com/document/d/1NZx2lktFOTpGH3Kzxcmdzbd6rOqRoQcNcAjWhCni6w8/edit?usp=sharing)
dotnet 6 is bundlied now so no need to have fast install. Also can do a few less steps.

I'll try to do a pull request but the problem is the download is only for folks with a license at this stage.

**Comment by jg00dman** [comment]
I am just running a final test on a Logos 10 install script... pull request to follow.

**Comment by jg00dman** [comment]
https://github.com/jg00dman/LogosLinuxInstaller/blob/master/install_Logos10_download.sh
Ok this works well I think.

**Comment by thw26** [comment]
> https://github.com/jg00dman/LogosLinuxInstaller/blob/master/install_Logos10_download.sh Ok this works well I think.

I have tested this install. It works.

**Comment by ferion11** [comment]
Thanks for the work :)

**Comment by jg00dman** [comment]
You're welcome!
