### ISSUE TITLE
Suggestion: use "-q" switch with winetricks for silent installs

### ISSUE THREAD

**Issue by rik-shaw** [ferion11/LogosLinuxInstaller#6]
Execute winetricks with "-q" so they can run non-interactive (like this: winetricks -q dotnet48)

**Comment by ferion11** [comment]
I had thought about it, but the lack of feedback bothered me. I'm thinking of adding this option to the main script, leaving everything optional.

**Comment by ferion11** [comment]
Done at 00963f71d9154373fb3fa99d6c65b05fc48e439e

**Comment by ferion11** [comment]
reverted this change (since certain compilation errors happens more often in the version with `"-q"`), but I added the `WINETRICKS_UNATTENDED` variable to install using the `"-q"` option.
```
$ WINETRICKS_UNATTENDED=1 ./install_AppImageWine_and_Logos.sh
```
