### ISSUE TITLE
Suggestion: combine winetricks installs (like for different fonts, etc.)

### ISSUE THREAD

**Issue by rik-shaw** [ferion11/LogosLinuxInstaller#7]
You can combine winetricks installs, like this: "winetricks arial andale calibri cambria candara"

**Comment by ferion11** [comment]
Yes (there is the "allfonts" too). But in this part, the user have to wait a good time, then to get more feedback, I have divided it in smaller steps (later I will create a bash function to let the code more clean, and give one better feedback to the user). I have to improve the quality of the code too.

**Comment by ferion11** [comment]
The v2.0 now only use `corefonts`: https://github.com/ferion11/LogosLinuxInstaller/blob/6c8f01cea4fbdc100a991bb9a4b93c22f12eb3e4/install_AppImageWine_and_Logos.sh#L548-L554
