### ISSUE TITLE
Possible Fix: previous layout not loading on startup

### ISSUE THREAD

**Issue by rik-shaw** [ferion11/LogosLinuxInstaller#9]
Possible Fix: Note that appending "LC_ALL=C" to the launcher may PREVENT saved layouts from loading on start, and makes Logos always open to the home screen. So we REMOVED that and I don't think there is any negative side-effect. You may want to test in your case, however before removing it.

**Comment by ferion11** [comment]
Indeed. The last wine 5.x have a better Unicode support, then I had planned to drop it after the next big update of the Wine_Appimage repo version.

**Comment by ferion11** [comment]
Removed LC_ALL=C at a43d6f7229a140c910f5eff72e715c2d9a39beb8
