### ISSUE TITLE
Install with app image no longer uses app image to run installer

### ISSUE THREAD

**Issue by jg00dman** [ferion11/LogosLinuxInstaller#93]
In the latest version of the script, when running the installer it actually used the host system wine instead of the appImage. On my system this caused a crash as the host system wine isn't compatible with Logos.

[terminaloutput.txt](https://github.com/ferion11/LogosLinuxInstaller/files/10056384/terminaloutput.txt)

**Comment by thw26** [comment]
Hmmm…. I'll have to read and see what's happening.
